import { PreparedFood } from '@/types/selectableItem';

//"drink" | "side_dish" | "snack_dessert" | "bakery" | "light_food"

/** 반찬/간식/보조식
 * 직접 조리 없이 바로 먹을 수 있는 상태의 음식.
 * 완결된 한 끼 식사 meal은 아니지만, 식사에 곁들이거나 간단히 먹거나 일부 경우 재료처럼 활용될 수 있는 중간층.
 * 하지만 보통 단독으로 “오늘의 식사” 메인 후보는 아님
 */

export const preparedFoodObj = {
  granola: {
    defaultStorage: 'pantry',
    expirationDays: {
      pantry: 180,
    },
    difficulty: 'easy',
    servingTemperature: 'warm',
    defaultUnitLabel: '봉',
    id: 'granola',
    label: '그래놀라',
    isActive: true,
    kind: 'preparedFood',
    category: 'light_food',
    unitOptions: ['봉', '상자', 'g'],
    synonyms: ['그라놀라', '오트그래놀라'],
  },
  yubu: {
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 7,
      freezer: 30,
    },
    difficulty: 'easy',
    servingTemperature: 'warm',
    defaultUnitLabel: '팩',
    id: 'yubu',
    label: '유부',
    isActive: true,
    kind: 'preparedFood',
    category: 'light_food',
    unitOptions: ['팩', '장', '개', 'g'],
    synonyms: ['유부초밥유부', '조미유부'],
  },
  natto: {
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 7,
      freezer: 30,
    },
    difficulty: 'easy',
    servingTemperature: 'warm',
    defaultUnitLabel: '팩',
    id: 'natto',
    label: '낫또',
    isActive: true,
    kind: 'preparedFood',
    category: 'light_food',
    unitOptions: ['팩', '장', '개', 'g'],
    synonyms: ['유부초밥유부', '조미유부'],
  },
  egg_baked: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'egg_baked',
    label: '훈제란',
    category: 'light_food',
    difficulty: 'easy',
    servingTemperature: 'either',
    synonyms: ['구운계란', '맥반석', '훈제달걀'],
  },
  egg_soft_boiled: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'egg_soft_boiled',
    label: '반숙란',
    category: 'light_food',
    difficulty: 'easy',
    servingTemperature: 'either',
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'egg' }],
      common: [],
      seasoning: [],
      optional: [],
    },
    synonyms: ['반숙', '반숙계란', '반숙달걀'],
  },
  aehobak_bokkeum: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'aehobak_bokkeum',
    label: '애호박볶음',
    category: 'side_dish',
    difficulty: 'easy',
    servingTemperature: 'cold',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'aehobak' }],
      common: [
        { kind: 'ingredient', id: 'onion' },
        { kind: 'ingredient', id: 'jjokpa' },
      ],
      seasoning: [
        { kind: 'ingredient', id: 'minced_garlic' },
        { kind: 'ingredient', id: 'salt' },
        { kind: 'ingredient', id: 'deulgireum' },
        { kind: 'ingredient', id: 'olive_oil' },
        { kind: 'ingredient', id: 'chamchi_aekjeot' },
      ],
      optional: [
        { kind: 'ingredient', id: 'cheongyang_gochu' },
        { kind: 'ingredient', id: 'bokkeun_chamkkae' },
      ],
    },
  },
  baechu_kimchi: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'baechu_kimchi',
    label: '배추김치',
    category: 'light_food',
    difficulty: 'medium',
    servingTemperature: 'cold',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'baechu' }],
      common: [{ kind: 'ingredient', id: 'mu' }],
      seasoning: [
        { kind: 'ingredient', id: 'minced_garlic' },
        { kind: 'ingredient', id: 'minced_ginger' },
        { kind: 'ingredient', id: 'myeolchi_aekjeot' },
        { kind: 'ingredient', id: 'salt' },
        { kind: 'ingredient', id: 'gochugaru' },
      ],
      optional: [],
    },
    synonyms: ['김치'],
  },
  baek_kimchi: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'baek_kimchi',
    label: '백김치',
    category: 'light_food',

    difficulty: 'medium',
    servingTemperature: 'cold',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'baechu' }],
      common: [
        { kind: 'ingredient', id: 'jjokpa' },
        { kind: 'ingredient', id: 'mu' },
        { kind: 'ingredient', id: 'bae' },
      ],
      seasoning: [
        { kind: 'ingredient', id: 'minced_garlic' },
        { kind: 'ingredient', id: 'salt' },
      ],
      optional: [],
    },
  },
  broccoli_bokkeum: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'broccoli_bokkeum',
    label: '브로콜리볶음',
    category: 'side_dish',

    difficulty: 'easy',
    servingTemperature: 'hot',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'broccoli' }],
      common: [{ kind: 'ingredient', id: 'garlic' }],
      seasoning: [
        { kind: 'ingredient', id: 'cooking_oil' },
        { kind: 'ingredient', id: 'salt' },
      ],
      optional: [],
    },
  },
  cheongpo_muk_muchim: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'cheongpo_muk_muchim',
    label: '청포묵무침',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'cold',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'cheongpo_muk' }],
      common: [
        { kind: 'ingredient', id: 'cucumber' },
        { kind: 'ingredient', id: 'carrot' },
      ],
      seasoning: [
        { kind: 'ingredient', id: 'soy_sauce' },
        { kind: 'ingredient', id: 'chamgireum' },
      ],
      optional: [{ kind: 'ingredient', id: 'gim' }],
    },
  },
  chicken_nuggets: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'chicken_nuggets',
    label: '치킨너겟',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'hot',
    availableFoodSources: ['takeout'],
  },
  chonggak_kimchi: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'chonggak_kimchi',
    label: '총각김치',
    category: 'light_food',

    difficulty: 'medium',
    servingTemperature: 'cold',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'chonggak_mu' }],
      common: [{ kind: 'ingredient', id: 'daepa' }],
      seasoning: [
        { kind: 'ingredient', id: 'gochugaru' },
        { kind: 'ingredient', id: 'myeolchi_aekjeot' },
        { kind: 'ingredient', id: 'minced_garlic' },
        { kind: 'ingredient', id: 'minced_ginger' },
      ],
      optional: [],
    },
  },
  chwi_namul: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'chwi_namul',
    label: '취나물',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'cold',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'chwinamul' }],
      common: [],
      seasoning: [
        { kind: 'ingredient', id: 'chamgireum' },
        { kind: 'ingredient', id: 'salt' },
      ],
      optional: [],
    },
  },
  dakttongjip_twigim: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'dakttongjip_twigim',
    label: '닭똥집튀김',
    category: 'light_food',

    difficulty: 'medium',
    servingTemperature: 'hot',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [
        { kind: 'ingredient', id: 'chicken_gizzard' },
        { kind: 'ingredient', id: 'twigim_garu' },
      ],
      common: [],
      seasoning: [
        { kind: 'ingredient', id: 'salt' },
        { kind: 'ingredient', id: 'black_pepper' },
      ],
      optional: [],
    },
    synonyms: ['근위튀김'],
  },
  danhobak_twigim: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'danhobak_twigim',
    label: '단호박튀김',
    category: 'light_food',

    difficulty: 'medium',
    servingTemperature: 'hot',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [
        { kind: 'ingredient', id: 'danhobak' },
        { kind: 'ingredient', id: 'twigim_garu' },
      ],
      common: [],
      seasoning: [{ kind: 'ingredient', id: 'cooking_oil' }],
      optional: [],
    },
  },

  danmuji: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'danmuji',
    label: '단무지',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'cold',

    availableFoodSources: ['takeout'],
  },

  deodeok_gui: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'deodeok_gui',
    label: '고추장 더덕구이',
    category: 'light_food',

    difficulty: 'medium',
    servingTemperature: 'hot',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [
        { kind: 'ingredient', id: 'deodeok' },
        { kind: 'ingredient', id: 'gochujang' },
      ],
      common: [],
      seasoning: [
        { kind: 'ingredient', id: 'gochugaru' },
        { kind: 'ingredient', id: 'soy_sauce' },
        { kind: 'ingredient', id: 'minced_garlic' },
        { kind: 'ingredient', id: 'chamgireum' },
      ],
      optional: [],
    },
    synonyms: ['더덕구이'],
  },

  frozen_mandu: {
    id: 'frozen_mandu',
    label: '냉동만두',
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    category: 'snack_dessert',

    difficulty: 'easy',
    servingTemperature: 'either',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [],
      common: [],
      seasoning: [],
      optional: [],
    },
    synonyms: ['만두튀김'],
  },

  gun_mandu: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'gun_mandu',
    label: '군만두',
    category: 'snack_dessert',

    difficulty: 'easy',
    servingTemperature: 'either',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'preparedFood', id: 'frozen_mandu' }],
      common: [],
      seasoning: [{ kind: 'ingredient', id: 'cooking_oil' }],
      optional: [],
    },
    synonyms: ['만두튀김'],
  },
  aehobak_jeon: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'aehobak_jeon',
    label: '애호박전',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'hot',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [
        { kind: 'ingredient', id: 'aehobak' },
        { kind: 'ingredient', id: 'egg' },
        { kind: 'ingredient', id: 'buchim_garu' },
      ],
      common: [],
      seasoning: [
        { kind: 'ingredient', id: 'salt' },
        { kind: 'ingredient', id: 'cooking_oil' },
      ],
      optional: [],
    },
  },
  donggeurangttaeng: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'donggeurangttaeng',
    label: '동그랑땡',
    category: 'light_food',

    difficulty: 'medium',
    servingTemperature: 'hot',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'ground_pork' }],
      common: [
        { kind: 'ingredient', id: 'dubu' },
        { kind: 'ingredient', id: 'onion' },
      ],
      seasoning: [
        { kind: 'ingredient', id: 'salt' },
        { kind: 'ingredient', id: 'black_pepper' },
        { kind: 'ingredient', id: 'cooking_oil' },
      ],
      optional: [],
    },
  },
  dongtae_jeon: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'dongtae_jeon',
    label: '동태전',
    category: 'light_food',

    difficulty: 'medium',
    servingTemperature: 'hot',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [
        { kind: 'ingredient', id: 'dongtae' },
        { kind: 'ingredient', id: 'egg' },
        { kind: 'ingredient', id: 'milgaru' },
      ],
      common: [],
      seasoning: [
        { kind: 'ingredient', id: 'salt' },
        { kind: 'ingredient', id: 'cooking_oil' },
      ],
      optional: [],
    },
  },
  doraji_muchim: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'doraji_muchim',
    label: '도라지무침',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'cold',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'doraji' }],
      common: [],
      seasoning: [
        { kind: 'ingredient', id: 'gochugaru' },
        { kind: 'ingredient', id: 'gochujang' },
        { kind: 'ingredient', id: 'minced_garlic' },
        { kind: 'ingredient', id: 'chamgireum' },
      ],
      optional: [],
    },
  },
  dotori_muk_muchim: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'dotori_muk_muchim',
    label: '도토리묵무침',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'cold',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'dotori_muk' }],
      common: [
        { kind: 'ingredient', id: 'cucumber' },
        { kind: 'ingredient', id: 'onion' },
      ],
      seasoning: [
        { kind: 'ingredient', id: 'gochugaru' },
        { kind: 'ingredient', id: 'soy_sauce' },
        { kind: 'ingredient', id: 'chamgireum' },
      ],
      optional: [],
    },
  },
  dubu_buchim: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'dubu_buchim',
    label: '두부부침',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'hot',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'dubu' }],
      common: [],
      seasoning: [
        { kind: 'ingredient', id: 'cooking_oil' },
        { kind: 'ingredient', id: 'salt' },
      ],
      optional: [],
    },
    synonyms: ['두부전'],
  },
  dubu_jorim: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'dubu_jorim',
    label: '두부조림',
    category: 'light_food',

    difficulty: 'medium',
    servingTemperature: 'hot',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'dubu' }],
      common: [{ kind: 'ingredient', id: 'daepa' }],
      seasoning: [
        { kind: 'ingredient', id: 'soy_sauce' },
        { kind: 'ingredient', id: 'gochugaru' },
        { kind: 'ingredient', id: 'minced_garlic' },
      ],
      optional: [],
    },
  },
  dwaeji_kkeopdegi: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'dwaeji_kkeopdegi',
    label: '돼지껍데기구이',
    category: 'light_food',

    difficulty: 'medium',
    servingTemperature: 'hot',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'pork_skin' }],
      common: [],
      seasoning: [],
      optional: [],
    },
  },
  eomuk_bokkeum: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'eomuk_bokkeum',
    label: '어묵볶음',
    category: 'light_food',
    difficulty: 'easy',
    servingTemperature: 'hot',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'eomuk' }],
      common: [
        { kind: 'ingredient', id: 'onion' },
        { kind: 'ingredient', id: 'carrot' },
        { kind: 'ingredient', id: 'daepa' },
      ],
      seasoning: [
        { kind: 'ingredient', id: 'soy_sauce' },
        { kind: 'ingredient', id: 'oligodang' },
        { kind: 'ingredient', id: 'cooking_oil' },
      ],
      optional: [],
    },
    synonyms: ['오뎅볶음'],
  },

  fried_egg: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'fried_egg',
    label: '계란프라이',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'hot',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'egg' }],
      common: [],
      seasoning: [{ kind: 'ingredient', id: 'cooking_oil' }],
      optional: [],
    },
    synonyms: ['계란후라이', '후라이'],
  },
  gaji_bokkeum: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'gaji_bokkeum',
    label: '가지볶음',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'hot',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'gaji' }],
      common: [{ kind: 'ingredient', id: 'onion' }],
      seasoning: [
        { kind: 'ingredient', id: 'soy_sauce' },
        { kind: 'ingredient', id: 'minced_garlic' },
        { kind: 'ingredient', id: 'cooking_oil' },
      ],
      optional: [],
    },
  },
  gamja_jeon: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'gamja_jeon',
    label: '감자전',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'hot',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'potato' }],
      common: [],
      seasoning: [
        { kind: 'ingredient', id: 'salt' },
        { kind: 'ingredient', id: 'cooking_oil' },
      ],
      optional: [],
    },
  },
  gamja_jorim: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'gamja_jorim',
    label: '감자조림',
    category: 'light_food',

    difficulty: 'medium',
    servingTemperature: 'either',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'potato' }],
      common: [],
      seasoning: [
        { kind: 'ingredient', id: 'soy_sauce' },
        { kind: 'ingredient', id: 'oligodang' },
      ],
      optional: [],
    },
    synonyms: ['알감자조림'],
  },
  gamja_twigim: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'gamja_twigim',
    label: '감자튀김',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'hot',

    availableFoodSources: ['takeout'],
    synonyms: ['프렌치프라이', '프렌치후라이'],
  },
  gamjachae_bokkeum: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'gamjachae_bokkeum',
    label: '감자채볶음',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'hot',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'potato' }],
      common: [],
      seasoning: [
        { kind: 'ingredient', id: 'salt' },
        { kind: 'ingredient', id: 'cooking_oil' },
      ],
      optional: [],
    },
  },
  ganjang_hwangtaechae_bokkeum: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'ganjang_hwangtaechae_bokkeum',
    label: '간장황태채볶음',
    category: 'light_food',

    difficulty: 'medium',
    servingTemperature: 'hot',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'hwangtaechae' }],
      common: [],
      seasoning: [
        { kind: 'ingredient', id: 'soy_sauce' },
        { kind: 'ingredient', id: 'oligodang' },
        { kind: 'ingredient', id: 'cooking_oil' },
      ],
      optional: [],
    },
  },
  gim_mari: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'gim_mari',
    label: '김말이',
    category: 'light_food',

    difficulty: 'medium',
    servingTemperature: 'hot',
    availableFoodSources: ['takeout'],
  },
  gimbugak: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'gimbugak',
    label: '김부각',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'hot',
    availableFoodSources: ['takeout'],
  },
  gimjaban: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'gimjaban',
    label: '김자반',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'cold',

    availableFoodSources: ['takeout'],
    synonyms: ['김가루'],
  },
  gochu_jangajji: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'gochu_jangajji',
    label: '고추장아찌',
    category: 'light_food',

    difficulty: 'medium',
    servingTemperature: 'cold',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'cheongyang_gochu' }],
      common: [],
      seasoning: [
        { kind: 'ingredient', id: 'soy_sauce' },
        { kind: 'ingredient', id: 'vinegar' },
        { kind: 'ingredient', id: 'sugar' },
      ],
      optional: [],
    },
    synonyms: ['고추절임'],
  },
  gochu_twigim: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'gochu_twigim',
    label: '고추튀김',
    category: 'light_food',

    difficulty: 'medium',
    servingTemperature: 'hot',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [
        { kind: 'ingredient', id: 'cheongyang_gochu' },
        { kind: 'ingredient', id: 'twigim_garu' },
      ],
      common: [],
      seasoning: [{ kind: 'ingredient', id: 'cooking_oil' }],
      optional: [],
    },
  },
  gochujang_hwangtaechae_bokkeum: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'gochujang_hwangtaechae_bokkeum',
    label: '고추장황태채볶음',
    category: 'light_food',

    difficulty: 'medium',
    servingTemperature: 'hot',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [
        { kind: 'ingredient', id: 'hwangtaechae' },
        { kind: 'ingredient', id: 'gochujang' },
      ],
      common: [],
      seasoning: [
        { kind: 'ingredient', id: 'oligodang' },
        { kind: 'ingredient', id: 'cooking_oil' },
      ],
      optional: [],
    },
  },
  goguma_twigim: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'goguma_twigim',
    label: '고구마튀김',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'hot',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [
        { kind: 'ingredient', id: 'sweet_potato' },
        { kind: 'ingredient', id: 'twigim_garu' },
      ],
      common: [],
      seasoning: [{ kind: 'ingredient', id: 'cooking_oil' }],
      optional: [],
    },
  },
  gosari_namul: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'gosari_namul',
    label: '고사리나물',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'cold',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'gosari' }],
      common: [],
      seasoning: [
        { kind: 'ingredient', id: 'minced_garlic' },
        { kind: 'ingredient', id: 'chamgireum' },
        { kind: 'ingredient', id: 'salt' },
      ],
      optional: [],
    },
  },
  gul_jeon: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'gul_jeon',
    label: '굴전',
    category: 'light_food',

    difficulty: 'medium',
    servingTemperature: 'hot',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [
        { kind: 'ingredient', id: 'saenggul' },
        { kind: 'ingredient', id: 'egg' },
      ],
      common: [{ kind: 'ingredient', id: 'milgaru' }],
      seasoning: [
        { kind: 'ingredient', id: 'cooking_oil' },
        { kind: 'ingredient', id: 'salt' },
      ],
      optional: [],
    },
  },
  gyeran_jang_jorim: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'gyeran_jang_jorim',
    label: '계란장조림',
    category: 'light_food',

    difficulty: 'medium',
    servingTemperature: 'cold',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'egg' }],
      common: [],
      seasoning: [
        { kind: 'ingredient', id: 'soy_sauce' },
        { kind: 'ingredient', id: 'oligodang' },
        { kind: 'ingredient', id: 'sugar' },
        { kind: 'ingredient', id: 'guk_ganjang' },
      ],
      optional: [{ kind: 'ingredient', id: 'cheongyang_gochu' }],
    },
    synonyms: ['달걀장조림'],
  },
  gyeran_jjim: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'gyeran_jjim',
    label: '계란찜',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'hot',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'egg' }],
      common: [],
      seasoning: [{ kind: 'ingredient', id: 'salt' }],
      optional: [{ kind: 'ingredient', id: 'daepa' }],
    },
    synonyms: ['달걀찜'],
  },
  gyeran_mari: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'gyeran_mari',
    label: '계란말이',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'hot',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'egg' }],
      common: [],
      seasoning: [{ kind: 'ingredient', id: 'salt' }],
      optional: [
        { kind: 'ingredient', id: 'daepa' },
        { kind: 'ingredient', id: 'carrot' },
      ],
    },
    synonyms: ['달걀말이'],
  },
  japchae: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'japchae',
    label: '잡채',
    category: 'light_food',

    difficulty: 'medium',
    servingTemperature: 'warm',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'dangmyeon' }],
      common: [
        { kind: 'ingredient', id: 'beef_hongdukkae' },
        { kind: 'ingredient', id: 'onion' },
        { kind: 'ingredient', id: 'carrot' },
        { kind: 'ingredient', id: 'sigeumchi' },
        { kind: 'ingredient', id: 'pyogo_beoseot' },
      ],
      seasoning: [
        { kind: 'ingredient', id: 'soy_sauce' },
        { kind: 'ingredient', id: 'chamgireum' },
        { kind: 'ingredient', id: 'sugar' },
      ],
      optional: [],
    },
  },

  jinmichae_bokkeum: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'jinmichae_bokkeum',
    label: '진미채볶음',
    category: 'light_food',

    difficulty: 'medium',
    servingTemperature: 'cold',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'ojingeochae' }],
      common: [],
      seasoning: [
        { kind: 'ingredient', id: 'gochujang' },
        { kind: 'ingredient', id: 'minced_garlic' },
        { kind: 'ingredient', id: 'matsul' },
        { kind: 'ingredient', id: 'oligodang' },
        { kind: 'ingredient', id: 'gochugaru' },
        { kind: 'ingredient', id: 'soy_sauce' },
      ],
      optional: [],
    },
    synonyms: ['오징어채'],
  },
  jomigim: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'jomigim',
    label: '조미김',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'cold',

    availableFoodSources: ['takeout'],
    synonyms: ['김'],
  },
  kimchi_bokkeum: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'kimchi_bokkeum',
    label: '김치볶음',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'hot',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'preparedFood', id: 'baechu_kimchi' }],
      common: [{ kind: 'ingredient', id: 'pork_belly' }],
      seasoning: [
        { kind: 'ingredient', id: 'cooking_oil' },
        { kind: 'ingredient', id: 'gochugaru' },
      ],
      optional: [],
    },
    synonyms: ['볶음김치'],
  },
  kkaennip_jangajji: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'kkaennip_jangajji',
    label: '깻잎장아찌',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'cold',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'kkaennip' }],
      common: [],
      seasoning: [
        { kind: 'ingredient', id: 'soy_sauce' },
        { kind: 'ingredient', id: 'vinegar' },
        { kind: 'ingredient', id: 'sugar' },
      ],
      optional: [],
    },
  },
  kkaennip_jeon: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'kkaennip_jeon',
    label: '깻잎전',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'hot',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [
        { kind: 'ingredient', id: 'kkaennip' },
        { kind: 'ingredient', id: 'buchim_garu' },
      ],
      common: [],
      seasoning: [
        { kind: 'ingredient', id: 'cooking_oil' },
        { kind: 'ingredient', id: 'salt' },
      ],
      optional: [
        { kind: 'ingredient', id: 'cooking_oil' },
        { kind: 'ingredient', id: 'salt' },
      ],
    },
  },
  kkakdugi: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'kkakdugi',
    label: '깍두기',
    category: 'light_food',

    difficulty: 'medium',
    servingTemperature: 'cold',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'mu' }],
      common: [{ kind: 'ingredient', id: 'daepa' }],
      seasoning: [
        { kind: 'ingredient', id: 'gochugaru' },
        { kind: 'ingredient', id: 'myeolchi_aekjeot' },
        { kind: 'ingredient', id: 'minced_garlic' },
        { kind: 'ingredient', id: 'minced_ginger' },
      ],
      optional: [],
    },
  },
  kkomak_muchim: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'kkomak_muchim',
    label: '꼬막무침',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'cold',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'kkomak' }],
      common: [
        { kind: 'ingredient', id: 'onion' },
        { kind: 'ingredient', id: 'carrot' },
        { kind: 'ingredient', id: 'buchu' },
      ],
      seasoning: [
        { kind: 'ingredient', id: 'gochugaru' },
        { kind: 'ingredient', id: 'soy_sauce' },
        { kind: 'ingredient', id: 'minced_garlic' },
        { kind: 'ingredient', id: 'chamgireum' },
      ],
      optional: [],
    },
  },
  kongjaban: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'kongjaban',
    label: '콩자반',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'cold',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'black_soybeans' }],
      common: [],
      seasoning: [
        { kind: 'ingredient', id: 'soy_sauce' },
        { kind: 'ingredient', id: 'oligodang' },
      ],
      optional: [],
    },
    synonyms: ['검은콩조림'],
  },
  kongnamul_muchim: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'kongnamul_muchim',
    label: '콩나물무침',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'cold',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'kongnamul' }],
      common: [],
      seasoning: [
        { kind: 'ingredient', id: 'minced_garlic' },
        { kind: 'ingredient', id: 'chamgireum' },
        { kind: 'ingredient', id: 'salt' },
      ],
      optional: [],
    },
  },
  korean_hotdog: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'korean_hotdog',
    label: '핫도그',
    category: 'snack_dessert',

    difficulty: 'easy',
    servingTemperature: 'hot',
    availableFoodSources: ['takeout'],
  },
  maneuljjong_bokkeum: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'maneuljjong_bokkeum',
    label: '마늘쫑볶음',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'hot',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'maneuljjong' }],
      common: [],
      seasoning: [
        { kind: 'ingredient', id: 'soy_sauce' },
        { kind: 'ingredient', id: 'cooking_oil' },
      ],
      optional: [],
    },
  },
  mechurial_jang_jorim: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'mechurial_jang_jorim',
    label: '메추리알장조림',
    category: 'light_food',

    difficulty: 'medium',
    servingTemperature: 'cold',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'quail_egg' }],
      common: [],
      seasoning: [
        { kind: 'ingredient', id: 'soy_sauce' },
        { kind: 'ingredient', id: 'oligodang' },
      ],
      optional: [],
    },
  },
  menbosha: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'menbosha',
    label: '멘보샤',
    category: 'light_food',

    difficulty: 'medium',
    servingTemperature: 'hot',
    availableFoodSources: ['takeout'],
  },
  mu_namul: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'mu_namul',
    label: '무나물',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'cold',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'mu' }],
      common: [],
      seasoning: [
        { kind: 'ingredient', id: 'deulgireum' },
        { kind: 'ingredient', id: 'minced_garlic' },
        { kind: 'ingredient', id: 'salt' },
      ],
      optional: [],
    },
  },

  mumallaengi: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'mumallaengi',
    label: '무말랭이',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'cold',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'mumallaengi' }],
      common: [],
      seasoning: [
        { kind: 'ingredient', id: 'gochugaru' },
        { kind: 'ingredient', id: 'soy_sauce' },
        { kind: 'ingredient', id: 'minced_garlic' },
        { kind: 'ingredient', id: 'sugar' },
      ],
      optional: [],
    },
  },
  musaengchae: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'musaengchae',
    label: '무생채',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'cold',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'mu' }],
      common: [],
      seasoning: [
        { kind: 'ingredient', id: 'gochugaru' },
        { kind: 'ingredient', id: 'myeolchi_aekjeot' },
        { kind: 'ingredient', id: 'minced_garlic' },
        { kind: 'ingredient', id: 'sugar' },
      ],
      optional: [],
    },
  },
  myeolchi_bokkeum: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'myeolchi_bokkeum',
    label: '멸치볶음',
    category: 'light_food',

    difficulty: 'medium',
    servingTemperature: 'cold',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'myeolchi' }],
      common: [],
      seasoning: [
        { kind: 'ingredient', id: 'oligodang' },
        { kind: 'ingredient', id: 'soy_sauce' },
        { kind: 'ingredient', id: 'cooking_oil' },
      ],
      optional: [],
    },
    synonyms: ['잔멸치볶음'],
  },
  myeongran_jeotgal: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'myeongran_jeotgal',
    label: '명란젓',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'cold',
    availableFoodSources: ['takeout'],
    synonyms: ['명란'],
  },
  nakji_jeotgal: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'nakji_jeotgal',
    label: '낙지젓',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'cold',
    availableFoodSources: ['takeout'],
    synonyms: ['낙지젓갈'],
  },
  neutari_beoseot_bokkeum: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'neutari_beoseot_bokkeum',
    label: '느타리버섯볶음',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'hot',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'neutari_beoseot' }],
      common: [{ kind: 'ingredient', id: 'onion' }],
      seasoning: [
        { kind: 'ingredient', id: 'soy_sauce' },
        { kind: 'ingredient', id: 'cooking_oil' },
        { kind: 'ingredient', id: 'minced_garlic' },
      ],
      optional: [],
    },
  },
  oi_muchim: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'oi_muchim',
    label: '오이무침',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'cold',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'cucumber' }],
      common: [],
      seasoning: [
        { kind: 'ingredient', id: 'gochugaru' },
        { kind: 'ingredient', id: 'vinegar' },
        { kind: 'ingredient', id: 'minced_garlic' },
        { kind: 'ingredient', id: 'sugar' },
      ],
      optional: [],
    },
  },
  ojingeo_twigim: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'ojingeo_twigim',
    label: '오징어튀김',
    category: 'light_food',

    difficulty: 'medium',
    servingTemperature: 'hot',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [
        { kind: 'ingredient', id: 'ojingeo' },
        { kind: 'ingredient', id: 'twigim_garu' },
      ],
      common: [],
      seasoning: [{ kind: 'ingredient', id: 'cooking_oil' }],
      optional: [],
    },
  },
  pa_kimchi: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'pa_kimchi',
    label: '파김치',
    category: 'light_food',

    difficulty: 'medium',
    servingTemperature: 'cold',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'jjokpa' }],
      common: [],
      seasoning: [
        { kind: 'ingredient', id: 'gochugaru' },
        { kind: 'ingredient', id: 'myeolchi_aekjeot' },
        { kind: 'ingredient', id: 'minced_garlic' },
        { kind: 'ingredient', id: 'minced_ginger' },
      ],
      optional: [],
    },
  },
  parae_gim: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'parae_gim',
    label: '파래김',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'cold',
    availableFoodSources: ['takeout'],
  },
  saeu_twigim: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'saeu_twigim',
    label: '새우튀김',
    category: 'light_food',

    difficulty: 'medium',
    servingTemperature: 'hot',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [
        { kind: 'ingredient', id: 'saeu' },
        { kind: 'ingredient', id: 'twigim_garu' },
      ],
      common: [],
      seasoning: [{ kind: 'ingredient', id: 'cooking_oil' }],
      optional: [],
    },
  },
  saeu_wanja: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'saeu_wanja',
    label: '새우완자',
    category: 'light_food',

    difficulty: 'medium',
    servingTemperature: 'hot',
    availableFoodSources: ['takeout'],
  },
  sausage_bokkeum: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'sausage_bokkeum',
    label: '소시지볶음',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'hot',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'sausage' }],
      common: [{ kind: 'ingredient', id: 'onion' }],
      seasoning: [
        { kind: 'ingredient', id: 'ketchup' },
        { kind: 'ingredient', id: 'cooking_oil' },
      ],
      optional: [],
    },
  },
  sigeumchi_namul: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'sigeumchi_namul',
    label: '시금치나물',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'cold',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'sigeumchi' }],
      common: [],
      seasoning: [
        { kind: 'ingredient', id: 'minced_garlic' },
        { kind: 'ingredient', id: 'chamgireum' },
        { kind: 'ingredient', id: 'salt' },
      ],
      optional: [],
    },
  },
  sogogi_jang_jorim: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'sogogi_jang_jorim',
    label: '소고기장조림',
    category: 'light_food',

    difficulty: 'medium',
    servingTemperature: 'cold',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'beef_round' }],
      common: [],
      seasoning: [
        { kind: 'ingredient', id: 'soy_sauce' },
        { kind: 'ingredient', id: 'oligodang' },
      ],
      optional: [],
    },
    synonyms: ['쇠고기장조림'],
  },
  sukjunamul_muchim: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'sukjunamul_muchim',
    label: '숙주나물무침',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'cold',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'sukjunamul' }],
      common: [],
      seasoning: [
        { kind: 'ingredient', id: 'minced_garlic' },
        { kind: 'ingredient', id: 'chamgireum' },
        { kind: 'ingredient', id: 'salt' },
      ],
      optional: [],
    },
  },

  tomato_gyeran_bokkeum: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'tomato_gyeran_bokkeum',
    label: '토마토계란볶음',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'hot',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [
        { kind: 'ingredient', id: 'tomato' },
        { kind: 'ingredient', id: 'egg' },
      ],
      common: [],
      seasoning: [
        { kind: 'ingredient', id: 'cooking_oil' },
        { kind: 'ingredient', id: 'salt' },
      ],
      optional: [],
    },
    synonyms: ['토마토달걀볶음'],
  },
  ueong_jorim: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'ueong_jorim',
    label: '우엉조림',
    category: 'light_food',

    difficulty: 'medium',
    servingTemperature: 'cold',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'ueong' }],
      common: [],
      seasoning: [
        { kind: 'ingredient', id: 'soy_sauce' },
        { kind: 'ingredient', id: 'oligodang' },
      ],
      optional: [],
    },
  },
  yangpa_jangajji: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'yangpa_jangajji',
    label: '양파장아찌',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'cold',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'onion' }],
      common: [],
      seasoning: [
        { kind: 'ingredient', id: 'soy_sauce' },
        { kind: 'ingredient', id: 'vinegar' },
        { kind: 'ingredient', id: 'sugar' },
      ],
      optional: [],
    },
  },
  yeongeun_jorim: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'yeongeun_jorim',
    label: '연근조림',
    category: 'light_food',

    difficulty: 'medium',
    servingTemperature: 'cold',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'yeongeun' }],
      common: [],
      seasoning: [
        { kind: 'ingredient', id: 'soy_sauce' },
        { kind: 'ingredient', id: 'oligodang' },
      ],
      optional: [],
    },
  },
  cheese_ball: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'cheese_ball',
    label: '치즈볼',
    category: 'snack_dessert',

    difficulty: 'easy',
    servingTemperature: 'either',
  },
  cheese_stick: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'cheese_stick',
    label: '치즈스틱',
    category: 'snack_dessert',

    difficulty: 'easy',
    servingTemperature: 'either',
  },
  corn_cheese: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'corn_cheese',
    label: '콘치즈',
    category: 'snack_dessert',

    difficulty: 'easy',
    servingTemperature: 'hot',

    foodStructure: {
      essential: [
        { kind: 'ingredient', id: 'mozzarella_cheese' },
        { kind: 'ingredient', id: 'canned_oksusu' },
      ],
      common: [],
      seasoning: [{ kind: 'ingredient', id: 'mayonnaise' }],
      optional: [],
    },
  },
  dak_kkochi: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'dak_kkochi',
    label: '닭꼬치',
    category: 'snack_dessert',

    difficulty: 'medium',
    servingTemperature: 'hot',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'chicken_leg' }],
      common: [],
      seasoning: [
        { kind: 'ingredient', id: 'gochujang' },
        { kind: 'ingredient', id: 'soy_sauce' },
        { kind: 'ingredient', id: 'oligodang' },
      ],
      optional: [],
    },
  },
  mattang: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'mattang',
    label: '맛탕',
    category: 'snack_dessert',

    difficulty: 'medium',
    servingTemperature: 'hot',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [
        { kind: 'ingredient', id: 'sweet_potato' },
        { kind: 'ingredient', id: 'mulyeot' },
      ],
      common: [],
      seasoning: [],
      optional: [],
    },
  },
  mul_mandu: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'mul_mandu',
    label: '물만두',
    category: 'snack_dessert',

    difficulty: 'easy',
    servingTemperature: 'hot',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'preparedFood', id: 'frozen_mandu' }],
      common: [],
      seasoning: [],
      optional: [],
    },
  },
  sundae: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'sundae',
    label: '순대',
    category: 'snack_dessert',

    difficulty: 'medium',
    servingTemperature: 'hot',
    availableFoodSources: ['takeout'],
    synonyms: ['찰순대'],
  },
  baechu_geotjeori: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'baechu_geotjeori',
    label: '배추겉절이',
    category: 'light_food',

    difficulty: 'medium',
    servingTemperature: 'cold',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'baechu' }],
      common: [
        { kind: 'ingredient', id: 'buchu' },
        { kind: 'ingredient', id: 'onion' },
      ],
      seasoning: [
        { kind: 'ingredient', id: 'gochugaru' },
        { kind: 'ingredient', id: 'minced_garlic' },
        { kind: 'ingredient', id: 'myeolchi_aekjeot' },
        { kind: 'ingredient', id: 'sugar' },
        { kind: 'ingredient', id: 'salt' },
      ],
      optional: [],
    },
  },
  buchu_geotjeori: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'buchu_geotjeori',
    label: '부추겉절이',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'cold',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'buchu' }],
      common: [],
      seasoning: [
        { kind: 'ingredient', id: 'gochugaru' },
        { kind: 'ingredient', id: 'myeolchi_aekjeot' },
        { kind: 'ingredient', id: 'minced_garlic' },
      ],
      optional: [],
    },
  },
  dongchimi: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'dongchimi',
    label: '동치미',
    category: 'light_food',

    difficulty: 'medium',
    servingTemperature: 'cold',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'mu' }],
      common: [{ kind: 'ingredient', id: 'jjokpa' }],
      seasoning: [{ kind: 'ingredient', id: 'salt' }],
      optional: [],
    },
  },
  maneul_jangajji: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'maneul_jangajji',
    label: '마늘장아찌',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'cold',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'garlic' }],
      common: [],
      seasoning: [
        { kind: 'ingredient', id: 'soy_sauce' },
        { kind: 'ingredient', id: 'vinegar' },
        { kind: 'ingredient', id: 'sugar' },
      ],
      optional: [],
    },
  },
  oi_sobagi: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'oi_sobagi',
    label: '오이소박이',
    category: 'light_food',

    difficulty: 'medium',
    servingTemperature: 'cold',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'cucumber' }],
      common: [
        { kind: 'ingredient', id: 'buchu' },
        { kind: 'ingredient', id: 'carrot' },
      ],
      seasoning: [
        { kind: 'ingredient', id: 'gochugaru' },
        { kind: 'ingredient', id: 'myeolchi_aekjeot' },
        { kind: 'ingredient', id: 'minced_garlic' },
        { kind: 'ingredient', id: 'minced_ginger' },
      ],
      optional: [],
    },
  },
  ojingeo_jeotgal: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'ojingeo_jeotgal',
    label: '오징어젓갈',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'cold',
    availableFoodSources: ['takeout'],
    synonyms: ['오징어젓'],
  },
  ssammu: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'ssammu',
    label: '쌈무',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'cold',

    availableFoodSources: ['takeout'],
  },

  yeolmu_kimchi: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'yeolmu_kimchi',
    label: '열무김치',
    category: 'light_food',

    difficulty: 'medium',
    servingTemperature: 'cold',
    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'yeolmu' }],
      common: [{ kind: 'ingredient', id: 'hong_gochu' }],
      seasoning: [{ kind: 'ingredient', id: 'gochugaru' }],
      optional: [],
    },
  },
  cooked_rice: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'cooked_rice',
    label: '밥',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'hot',

    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'baekmi' }],
      common: [],
      seasoning: [],
      optional: [],
    },
    synonyms: ['햇반'],
  },
  boiled_egg: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'boiled_egg',
    label: '삶은계란',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'either',

    foodStructure: {
      essential: [{ kind: 'ingredient', id: 'egg' }],
      common: [],
      seasoning: [],
      optional: [],
    },
    synonyms: ['삶은달걀', '감동란'],
  },
  cereal: {
    defaultUnitLabel: '개',
    defaultStorage: 'fridge',
    expirationDays: {
      fridge: 3,
    },
    kind: 'preparedFood',
    isActive: true,
    id: 'cereal',
    label: '시리얼',
    category: 'light_food',

    difficulty: 'easy',
    servingTemperature: 'cold',

    availableFoodSources: ['takeout'],
    foodStructure: {
      essential: [{ kind: 'preparedFood', id: 'cereal' }],
      common: [{ kind: 'ingredient', id: 'milk' }],
      seasoning: [],
      optional: [],
    },
  },

  chocolate_jam: {
    id: 'chocolate_jam',
    label: '초코잼',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 180, fridge: 180 },
    defaultUnitLabel: '통',
    unitOptions: ['통', '병', '개'],
    synonyms: ['초콜릿잼', '초코스프레드'],
  },
  black_sesame_tteok: {
    id: 'black_sesame_tteok',
    label: '흑임자떡',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 30 },
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },
  cake_slice: {
    id: 'cake_slice',
    label: '조각케이크',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 30 },
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },
  caramel: {
    id: 'caramel',
    label: '카라멜',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 90 },
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },
  chapssal_tteok: {
    id: 'chapssal_tteok',
    label: '찹쌀떡',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 30 },
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },
  chips: {
    id: 'chips',
    label: '칩',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 90 },
    defaultUnitLabel: '봉',
    unitOptions: ['봉', '상자'],
    synonyms: ['감자칩'],
  },
  choco_bar: {
    id: 'choco_bar',
    label: '초코바',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 90 },
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },
  chocolate: {
    id: 'chocolate',
    label: '초콜렛',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 90 },
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },
  chocolate_bar: {
    id: 'chocolate_bar',
    label: '초콜렛바',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 90 },
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },
  cookie: {
    id: 'cookie',
    label: '쿠키',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 90 },
    defaultUnitLabel: '봉',
    unitOptions: ['봉', '상자'],
  },
  cracker: {
    id: 'cracker',
    label: '크래커',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 90 },
    defaultUnitLabel: '봉',
    unitOptions: ['봉', '상자'],
  },
  dried_persimmon: {
    id: 'dried_persimmon',
    label: '곶감',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 30 },
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },
  energy_bar: {
    id: 'energy_bar',
    label: '에너지바',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 90 },
    defaultUnitLabel: '봉',
    unitOptions: ['봉', '상자'],
  },
  garaetteok: {
    id: 'garaetteok',
    label: '가래떡',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'fridge',
    expirationDays: { pantry: 30 },
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },

  grape_jam: {
    id: 'grape_jam',
    label: '포도잼',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 14 },
    defaultUnitLabel: '병',
    unitOptions: ['병', '통'],
  },
  hangwa: {
    id: 'hangwa',
    label: '한과',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 30 },
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },
  honey_rice_cake: {
    id: 'honey_rice_cake',
    label: '꿀떡',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'fridge',
    expirationDays: { pantry: 30 },
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },
  ice_cream_bar: {
    id: 'ice_cream_bar',
    label: '아이스크림바',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 30 },
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },
  ice_cream_tub: {
    id: 'ice_cream_tub',
    label: '아이스크림통',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'freezer',
    expirationDays: { freezer: 180 },
    defaultUnitLabel: '통',
    unitOptions: ['통', '개'],
  },
  injeolmi: {
    id: 'injeolmi',
    label: '인절미떡',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 30 },
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },
  jelly: {
    id: 'jelly',
    label: '젤리',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 90 },
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },
  marshmallow: {
    id: 'marshmallow',
    label: '마시멜로우',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 30 },
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },

  nachos: {
    id: 'nachos',
    label: '나쵸',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 30 },
    defaultUnitLabel: '봉',
    unitOptions: ['봉', '상자'],
  },
  omegi_tteok: {
    id: 'omegi_tteok',
    label: '오메기떡',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'fridge',
    expirationDays: { pantry: 30 },
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },
  oranda: {
    id: 'oranda',
    label: '오란다',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 30 },
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },
  pancake: {
    id: 'pancake',
    label: '팬케이크',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 5 },
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
    synonyms: ['핫케이크'],
  },
  peanut_butter: {
    id: 'peanut_butter',
    label: '땅콩잼',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 30 },
    defaultUnitLabel: '병',
    unitOptions: ['병', '통'],
  },

  popcorn: {
    id: 'popcorn',
    label: '팝콘',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 90 },
    defaultUnitLabel: '봉',
    unitOptions: ['봉', '상자'],
  },

  pudding: {
    id: 'pudding',
    label: '푸딩',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 30 },
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },
  rice_cracker: {
    id: 'rice_cracker',
    label: '쌀과자',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 30 },
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },

  sandwich_cookie: {
    id: 'sandwich_cookie',
    label: '샌드쿠키',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 90 },
    defaultUnitLabel: '봉',
    unitOptions: ['봉', '상자'],
    synonyms: ['오레오'],
  },

  strawberry_jam: {
    id: 'strawberry_jam',
    label: '딸기잼',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 14 },
    defaultUnitLabel: '병',
    unitOptions: ['병', '통'],
  },
  whole_cake: {
    id: 'whole_cake',
    label: '홀케이크',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 30 },
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
    synonyms: ['케잌', '홀케잌'],
  },
  yokan: {
    id: 'yokan',
    label: '양갱',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 30 },
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },
  yugwa: {
    id: 'yugwa',
    label: '유과',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 30 },
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },

  bagel: {
    id: 'bagel',
    label: '베이글',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 5 },
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },
  baguette: {
    id: 'baguette',
    label: '바게뜨',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 5 },
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },
  castella: {
    id: 'castella',
    label: '카스테라',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 5 },
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },
  cinnamon_roll: {
    id: 'cinnamon_roll',
    label: '시나몬롤',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 30 },
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },
  croissant: {
    id: 'croissant',
    label: '크로와상',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 5 },
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },
  dinner_roll: {
    id: 'dinner_roll',
    label: '모닝빵',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 30 },
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },
  donut: {
    id: 'donut',
    label: '도넛',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 5 },
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },
  garlic_bread: {
    id: 'garlic_bread',
    label: '마늘빵',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 5 },
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },
  muffin: {
    id: 'muffin',
    label: '머핀',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 5 },
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },
  pie: {
    id: 'pie',
    label: '파이',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 30 },
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },
  pretzel: {
    id: 'pretzel',
    label: '프레첼',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 90 },
    defaultUnitLabel: '봉',
    unitOptions: ['봉', '상자'],
  },
  red_bean_bread: {
    id: 'red_bean_bread',
    label: '단팥빵',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 5 },
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },

  roll_cake: {
    id: 'roll_cake',
    label: '롤케이크',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 30 },
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },
  rye_bread: {
    id: 'rye_bread',
    label: '호밀빵',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 5 },
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },
  salt_bread: {
    id: 'salt_bread',
    label: '소금빵',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 5 },
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },
  sandwich_bread: {
    id: 'sandwich_bread',
    label: '식빵',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 5 },
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },
  steamed_bun: {
    id: 'steamed_bun',
    label: '찐빵',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 30 },
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },
  tart: {
    id: 'tart',
    label: '타르트',
    isActive: true,
    kind: 'preparedFood',
    category: 'snack_dessert',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 30 },
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },

  kong_mul: {
    id: 'kong_mul',
    label: '콩물',
    isActive: true,
    kind: 'preparedFood',
    category: 'drink',
    defaultStorage: 'fridge',
    expirationDays: { fridge: 5, freezer: 30 },
    defaultUnitLabel: '병',
    unitOptions: ['병', '팩', '개'],
    packageWeight: { amount: 500, unit: 'ml' },
    synonyms: ['콩국물', '콩국수콩물'],
  },
  banana_milk: {
    id: 'banana_milk',
    label: '바나나우유',
    isActive: true,
    kind: 'preparedFood',
    category: 'drink',
    defaultStorage: 'fridge',
    expirationDays: { fridge: 7 },
    defaultUnitLabel: '팩',
    unitOptions: ['팩', '병'],
  },
  beer: {
    id: 'beer',
    label: '맥주',
    isActive: true,
    kind: 'preparedFood',
    category: 'drink',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 365 },
    defaultUnitLabel: '병',
    unitOptions: ['병', '캔'],
  },
  chocolate_milk: {
    id: 'chocolate_milk',
    label: '초코우유',
    isActive: true,
    kind: 'preparedFood',
    category: 'drink',
    defaultStorage: 'fridge',
    expirationDays: { fridge: 7 },
    defaultUnitLabel: '팩',
    unitOptions: ['팩', '병'],
  },
  can_coffee: {
    id: 'can_coffee',
    label: '캔커피',
    isActive: true,
    kind: 'preparedFood',
    category: 'drink',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 365 },
    defaultUnitLabel: '캔',
    unitOptions: ['캔', '팩'],
  },
  can_cola: {
    id: 'can_cola',
    label: '캔콜라',
    isActive: true,
    kind: 'preparedFood',
    category: 'drink',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 365 },
    defaultUnitLabel: '캔',
    unitOptions: ['캔', '팩'],
  },
  coffee_milk: {
    id: 'coffee_milk',
    label: '커피우유',
    isActive: true,
    kind: 'preparedFood',
    category: 'drink',
    defaultStorage: 'fridge',
    expirationDays: { fridge: 7 },
    defaultUnitLabel: '팩',
    unitOptions: ['팩', '병'],
  },
  drink_yogurt: {
    id: 'drink_yogurt',
    label: '요구르트',
    isActive: true,
    kind: 'preparedFood',
    category: 'drink',
    defaultStorage: 'fridge',
    expirationDays: { fridge: 7 },
    defaultUnitLabel: '병',
    unitOptions: ['병', '캔'],
  },
  energy_drink: {
    id: 'energy_drink',
    label: '에너지드링크',
    isActive: true,
    kind: 'preparedFood',
    category: 'drink',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 180 },
    defaultUnitLabel: '병',
    unitOptions: ['병', '캔'],
    synonyms: ['몬스터에너지', '핫식스', '클룹', '레드불'],
  },
  gwachae_juice: {
    id: 'gwachae_juice',
    label: '과채주스',
    isActive: true,
    kind: 'preparedFood',
    category: 'drink',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 180 },
    defaultUnitLabel: '팩',
    unitOptions: ['팩', '병'],
  },
  ion_drink: {
    id: 'ion_drink',
    label: '이온음료',
    isActive: true,
    kind: 'preparedFood',
    category: 'drink',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 180 },
    defaultUnitLabel: '병',
    unitOptions: ['병', '캔'],
  },
  makgeolli: {
    id: 'makgeolli',
    label: '막걸리',
    isActive: true,
    kind: 'preparedFood',
    category: 'drink',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 180 },
    defaultUnitLabel: '팩',
    unitOptions: ['팩', '병'],
  },
  protein_drink: {
    id: 'protein_drink',
    label: '프로틴음료',
    isActive: true,
    kind: 'preparedFood',
    category: 'drink',
    defaultStorage: 'fridge',
    expirationDays: { fridge: 14 },
    defaultUnitLabel: '팩',
    unitOptions: ['팩', '병'],
  },
  soju: {
    id: 'soju',
    label: '소주',
    isActive: true,
    kind: 'preparedFood',
    category: 'drink',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 365 },
    defaultUnitLabel: '병',
    unitOptions: ['병', '캔'],
  },
  soy_milk: {
    id: 'soy_milk',
    label: '두유',
    isActive: true,
    kind: 'preparedFood',
    category: 'drink',
    defaultStorage: 'fridge',
    expirationDays: { fridge: 14 },
    defaultUnitLabel: '팩',
    unitOptions: ['팩', '병'],
  },
  sparkling_water: {
    id: 'sparkling_water',
    label: '탄산수',
    isActive: true,
    kind: 'preparedFood',
    category: 'drink',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 365 },
    defaultUnitLabel: '병',
    unitOptions: ['병', '캔'],
  },
  strawberry_milk: {
    id: 'strawberry_milk',
    label: '딸기우유',
    isActive: true,
    kind: 'preparedFood',
    category: 'drink',
    defaultStorage: 'fridge',
    expirationDays: { fridge: 7 },
    defaultUnitLabel: '팩',
    unitOptions: ['팩', '병'],
  },
  tea_bag: {
    id: 'tea_bag',
    label: '티백',
    isActive: true,
    kind: 'preparedFood',
    category: 'drink',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 365 },
    defaultUnitLabel: '상자',
    unitOptions: ['상자', '봉'],
  },
  bottled_water: {
    id: 'bottled_water',
    label: '생수',
    isActive: true,
    kind: 'preparedFood',
    category: 'drink',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 365 },
    defaultUnitLabel: '병',
    unitOptions: ['병', '캔'],
  },
  whiskey: {
    id: 'whiskey',
    label: '위스키',
    isActive: true,
    kind: 'preparedFood',
    category: 'drink',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 365 },
    defaultUnitLabel: '병',
    unitOptions: ['병', '캔'],
  },
  wine: {
    id: 'wine',
    label: '와인',
    isActive: true,
    kind: 'preparedFood',
    category: 'drink',
    defaultStorage: 'pantry',
    expirationDays: { pantry: 365 },
    defaultUnitLabel: '병',
    unitOptions: ['병', '캔'],
  },
} as const;

export const allPreparedFoodList: PreparedFood[] = Object.values(preparedFoodObj);
