import { StorageItem, CustomStorageItem } from '@/types/storage';
import { DEFAULT_EXPIRATION_DAYS } from '@/constants/storage/storageObj';
import { formatDateString } from '@/utils/formatDate';
import { addDays } from 'date-fns';
import { nanoid } from 'nanoid/non-secure';

export const mockStorageItemList: StorageItem[] = [
  {
    type: 'ingredient',
    id: '1',
    ingredientId: 'egg',
    purchasedAt: '2026-03-01',
    expiresAt: '2026-04-25',
    storage: { type: 'fridge', side: 'inner', section: '1' },
    memo: '유정란',
  },
  {
    type: 'ingredient',
    id: '2',
    ingredientId: 'daepa',
    purchasedAt: '2026-03-03',
    expiresAt: '2026-05-21',
    storage: { type: 'fridge', side: 'inner', section: '1' },
  },
  {
    type: 'ingredient',
    id: '3',
    ingredientId: 'sigeumchi',
    purchasedAt: '2026-03-02',
    expiresAt: '2026-08-21',
    storage: { type: 'fridge', side: 'inner', section: '1' },
  },
  {
    type: 'ingredient',
    id: '4',
    ingredientId: 'broccoli',
    purchasedAt: '2026-03-01',
    expiresAt: '2026-08-21',
    storage: { type: 'fridge', side: 'inner', section: '1' },
  },
  {
    type: 'ingredient',
    id: '4-potato',
    ingredientId: 'potato',
    purchasedAt: '2026-03-01',
    expiresAt: '2026-04-26',
    storage: { type: 'fridge', side: 'inner', section: '1' },
  },
  {
    type: 'ingredient',
    id: '5',
    ingredientId: 'aehobak',
    purchasedAt: '2026-03-02',
    expiresAt: '2026-06-11',
    storage: { type: 'fridge', side: 'inner', section: '1' },
  },
  {
    type: 'ingredient',
    id: '6',
    ingredientId: 'pyogo_beoseot',
    purchasedAt: '2026-03-03',
    expiresAt: '2026-08-21',
    storage: { type: 'fridge', side: 'inner', section: '1' },
  },

  {
    type: 'ingredient',
    id: '10',
    ingredientId: 'cheongyang_gochu',
    purchasedAt: '2026-03-02',
    expiresAt: '2026-08-21',
    storage: { type: 'fridge', side: 'inner', section: '1' },
  },
  {
    type: 'ingredient',
    id: '12',
    ingredientId: 'chicken_breast',
    purchasedAt: '2026-02-25',
    expiresAt: '2026-08-10',
    storage: { type: 'freezer', side: 'inner', section: '1' },
  },
  {
    type: 'ingredient',
    id: 'chicken_leg',
    ingredientId: 'chicken_leg',
    purchasedAt: '2026-02-25',
    expiresAt: '2026-04-27',
    storage: { type: 'freezer', side: 'inner', section: '1' },
  },
  {
    type: 'ingredient',
    id: '13',
    ingredientId: 'duck_slice',
    purchasedAt: '2026-02-28',
    expiresAt: '2026-08-20',
    storage: { type: 'freezer', side: 'inner', section: '1' },
  },
  {
    type: 'ingredient',
    id: '14',
    ingredientId: 'duck_slice_smoked',
    purchasedAt: '2026-02-25',
    expiresAt: '2026-05-01',
    storage: { type: 'freezer', side: 'inner', section: '1' },
  },
  {
    type: 'ingredient',
    id: '15',
    ingredientId: 'beef_brisket',
    purchasedAt: '2026-06-11',
    expiresAt: '2026-06-12',
    storage: { type: 'freezer', side: 'inner', section: '1' },
  },
  {
    type: 'ingredient',
    id: '17',
    ingredientId: 'pork_neck',
    purchasedAt: '2026-02-27',
    expiresAt: '2026-06-27',
    storage: { type: 'freezer', side: 'inner', section: '1' },
  },
  {
    type: 'ingredient',
    id: '18',
    ingredientId: 'baby_leaf',
    purchasedAt: '2026-02-21',
    expiresAt: '2026-07-25',
    storage: { type: 'fridge', side: 'inner', section: '1' },
  },
  {
    type: 'ingredient',
    id: '19',
    ingredientId: 'beef_brisket',
    purchasedAt: '2026-02-22',
    expiresAt: '2026-07-25',
    storage: { type: 'freezer', side: 'inner', section: '1' },
  },
  {
    type: 'ingredient',
    id: '20',
    ingredientId: 'pork_belly',
    purchasedAt: '2026-02-24',
    expiresAt: '2026-07-28',
    storage: { type: 'freezer', side: 'inner', section: '1' },
  },

  {
    type: 'ingredient',
    id: '21',
    ingredientId: 'spaghetti_myeon',
    purchasedAt: '2026-04-28',
    expiresAt: '2028-05-20',
    storage: { type: 'pantry', side: 'inner', section: '1' },
  },
  {
    type: 'ingredient',
    id: '22',
    ingredientId: 'fusilli',
    purchasedAt: '2026-02-15',
    expiresAt: '2028-02-15',
    storage: { type: 'pantry', side: 'inner', section: '1' },
  },
  {
    type: 'ingredient',
    id: '23',
    ingredientId: 'memil_garu',
    purchasedAt: '2026-02-18',
    expiresAt: '2027-05-18',
    storage: { type: 'pantry', side: 'inner', section: '1' },
  },
  {
    type: 'ingredient',
    id: '24',
    ingredientId: 'ssal_guksu_myeon',
    purchasedAt: '2026-02-19',
    expiresAt: '2027-04-19',
    storage: { type: 'pantry', side: 'inner', section: '1' },
  },
  {
    type: 'ingredient',
    id: '25',
    ingredientId: 'dangmyeon',
    purchasedAt: '2026-02-15',
    expiresAt: '2028-06-15',
    storage: { type: 'pantry', side: 'inner', section: '1' },
  },
  {
    type: 'ingredient',
    id: '26',
    ingredientId: 'rice_paper',
    purchasedAt: '2026-02-10',
    expiresAt: '2027-04-10',
    storage: { type: 'pantry', side: 'inner', section: '1' },
  },
  {
    type: 'ingredient',
    id: '27',
    ingredientId: 'tortilla',
    purchasedAt: '2026-03-01',
    expiresAt: '2026-03-31',
    storage: { type: 'fridge', side: 'inner', section: '1' },
  },
  {
    type: 'ingredient',
    id: '28',
    ingredientId: 'mandupi',
    purchasedAt: '2026-03-02',
    expiresAt: '2026-05-17',
    storage: { type: 'fridge', side: 'inner', section: '1' },
  },
  {
    type: 'ingredient',
    id: '29',
    ingredientId: 'tteokbokki_tteok',
    purchasedAt: '2026-03-03',
    expiresAt: '2026-08-10',
    storage: { type: 'fridge', side: 'inner', section: '1' },
  },
  {
    type: 'ingredient',
    id: '30',
    ingredientId: 'kal_guksu_myeon',
    purchasedAt: '2026-03-02',
    expiresAt: '2026-06-01',
    storage: { type: 'fridge', side: 'inner', section: '1' },
  },
];

const now = new Date();

export const initialCustomStorageItem: CustomStorageItem = {
  type: 'custom',
  id: nanoid(),
  customLabel: '',
  storage: { type: 'fridge' as const },
  purchasedAt: formatDateString(now, 'yyyy-MM-dd'),
  expiresAt: formatDateString(addDays(now, DEFAULT_EXPIRATION_DAYS), 'yyyy-MM-dd'),
  memo: '',
};
