import { Category } from '@/constants/category';
import { ImageSourcePropType } from 'react-native';

const noodleObj = {
  udon_noodle: {
    id: 'udon_noodle',
    label: '우동면',
    isActive: true,
    categories: ['noodle'],
    defaultStorage: 'fridge',
    expirationDays: 30,
    defaultUnitLabel: '봉',
    unitOptions: ['봉', '팩'],
    synonyms: ['우동면', '우동사리', '우동'],
  },

  gamja_ongsimi: {
    id: 'gamja_ongsimi',
    label: '감자옹심이',
    isActive: true,
    categories: ['noodle'],
    defaultStorage: 'fridge',
    expirationDays: 30,
    defaultUnitLabel: '봉',
    unitOptions: ['봉', '팩'],
    synonyms: ['옹심이'],
  },

  tortilla: {
    id: 'tortilla',
    label: '또띠아',
    isActive: true,
    categories: ['noodle'],
    defaultStorage: 'fridge',
    expirationDays: 30,
    defaultUnitLabel: '팩',
    unitOptions: ['팩', '봉'],
    synonyms: ['토르티야', '랩'],
  },

  fusilli: {
    id: 'fusilli',
    label: '푸실리',
    isActive: true,
    categories: ['noodle'],
    defaultStorage: 'pantry',
    expirationDays: 730,
    defaultUnitLabel: '봉',
    unitOptions: ['봉', '팩'],
    synonyms: ['파스타'],
  },

  spaghetti_noodle: {
    id: 'spaghetti_noodle',
    label: '스파게티면',
    isActive: true,
    categories: ['noodle'],
    defaultStorage: 'pantry',
    expirationDays: 730,
    defaultUnitLabel: '봉',
    unitOptions: ['봉', '팩'],
    synonyms: ['스파게티', '파스타면'],
  },

  tteokbokki_ricecake: {
    id: 'tteokbokki_ricecake',
    label: '떡볶이떡',
    isActive: true,
    categories: ['noodle'],
    defaultStorage: 'fridge',
    expirationDays: 7,
    defaultUnitLabel: '봉',
    unitOptions: ['봉', '팩'],
    synonyms: ['밀떡', '쌀떡'],
  },

  penne: {
    id: 'penne',
    label: '펜네',
    isActive: true,
    categories: ['noodle'],
    defaultStorage: 'pantry',
    expirationDays: 730,
    defaultUnitLabel: '봉',
    unitOptions: ['봉', '팩'],
    synonyms: ['펜네파스타'],
  },

  tteok_soup_ricecake: {
    id: 'tteok_soup_ricecake',
    label: '떡국떡',
    isActive: true,
    categories: ['noodle'],
    defaultStorage: 'fridge',
    expirationDays: 3,
    defaultUnitLabel: '봉',
    unitOptions: ['봉', '팩'],
    synonyms: ['떡국용떡'],
  },

  sujebi_noodle: {
    id: 'sujebi_noodle',
    label: '수제비',
    isActive: true,
    categories: ['noodle'],
    defaultStorage: 'fridge',
    expirationDays: 14,
    defaultUnitLabel: '봉',
    unitOptions: ['봉', '팩'],
    synonyms: ['수제비반죽'],
  },

  rice_noodle: {
    id: 'rice_noodle',
    label: '쌀국수면',
    isActive: true,
    categories: ['noodle'],
    defaultStorage: 'pantry',
    expirationDays: 365,
    defaultUnitLabel: '봉',
    unitOptions: ['봉', '팩'],
    synonyms: ['포면'],
  },

  konjac_noodle: {
    id: 'konjac_noodle',
    label: '곤약면',
    isActive: true,
    categories: ['noodle'],
    defaultStorage: 'fridge',
    expirationDays: 30,
    defaultUnitLabel: '봉',
    unitOptions: ['봉', '팩'],
    synonyms: ['곤약국수'],
  },

  buckwheat_noodle: {
    id: 'buckwheat_noodle',
    label: '메밀면',
    isActive: true,
    categories: ['noodle'],
    defaultStorage: 'pantry',
    expirationDays: 365,
    defaultUnitLabel: '봉',
    unitOptions: ['봉', '팩'],
    synonyms: ['소바면'],
  },

  dumpling_wrapper: {
    id: 'dumpling_wrapper',
    label: '만두피',
    isActive: true,
    categories: ['noodle'],
    defaultStorage: 'fridge',
    expirationDays: 15,
    defaultUnitLabel: '팩',
    unitOptions: ['팩', '봉'],
    synonyms: ['만두용피'],
  },

  kalguksu_noodle: {
    id: 'kalguksu_noodle',
    label: '칼국수면',
    isActive: true,
    categories: ['noodle'],
    defaultStorage: 'fridge',
    expirationDays: 30,
    defaultUnitLabel: '봉',
    unitOptions: ['봉', '팩'],
    synonyms: ['칼국수'],
  },

  naengmyeon: {
    id: 'naengmyeon',
    label: '냉면',
    isActive: true,
    categories: ['noodle'],
    defaultStorage: 'fridge',
    expirationDays: 30,
    defaultUnitLabel: '봉',
    unitOptions: ['봉', '팩'],
    synonyms: ['냉면사리'],
  },

  chinese_noodle: {
    id: 'chinese_noodle',
    label: '중화면',
    isActive: true,
    categories: ['noodle'],
    defaultStorage: 'fridge',
    expirationDays: 30,
    defaultUnitLabel: '봉',
    unitOptions: ['봉', '팩'],
    synonyms: ['짜장면'],
  },

  rice_paper: {
    id: 'rice_paper',
    label: '라이스페이퍼',
    isActive: true,
    categories: ['noodle'],
    defaultStorage: 'pantry',
    expirationDays: 365,
    defaultUnitLabel: '팩',
    unitOptions: ['팩', '봉'],
    synonyms: ['월남쌈피'],
  },

  flat_glass_noodle: {
    id: 'flat_glass_noodle',
    label: '납작당면',
    isActive: true,
    categories: ['noodle'],
    defaultStorage: 'pantry',
    expirationDays: 730,
    defaultUnitLabel: '봉',
    unitOptions: ['봉', '팩'],
    synonyms: ['중국당면'],
  },
} as const;

const vegetableObj = {
  radish: {
    id: 'radish',
    label: '무',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 14,
    defaultUnitLabel: '개',
    unitOptions: ['개', '단'],
  },

  eggplant: {
    id: 'eggplant',
    label: '가지',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 5,
    defaultUnitLabel: '개',
    unitOptions: ['개'],
  },

  green_onion: {
    id: 'green_onion',
    label: '대파',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 7,
    defaultUnitLabel: '단',
    unitOptions: ['단', '묶음', '개'],
  },

  napa: {
    id: 'napa',
    label: '배추',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 10,
    defaultUnitLabel: '포기',
    unitOptions: ['포기', '개'],
  },

  chive: {
    id: 'chive',
    label: '부추',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 4,
    defaultUnitLabel: '단',
    unitOptions: ['단', '묶음'],
  },

  beet: {
    id: 'beet',
    label: '비트',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 14,
    defaultUnitLabel: '개',
    unitOptions: ['개'],
  },

  cucumber: {
    id: 'cucumber',
    label: '오이',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 5,
    defaultUnitLabel: '개',
    unitOptions: ['개'],
  },

  potato: {
    id: 'potato',
    label: '감자',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'pantry',
    expirationDays: 30,
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },

  chard: {
    id: 'chard',
    label: '근대',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 4,
    defaultUnitLabel: '묶음',
    unitOptions: ['묶음', '단'],
  },

  naengi: {
    id: 'naengi',
    label: '냉이',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 3,
    defaultUnitLabel: '묶음',
    unitOptions: ['묶음', '단'],
  },

  dallae: {
    id: 'dallae',
    label: '달래',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 3,
    defaultUnitLabel: '묶음',
    unitOptions: ['묶음', '단'],
  },

  garlic: {
    id: 'garlic',
    label: '마늘',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'pantry',
    expirationDays: 60,
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },

  leaf_lettuce: {
    id: 'leaf_lettuce',
    label: '상추',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 3,
    defaultUnitLabel: '묶음',
    unitOptions: ['묶음', '단'],
  },

  onion: {
    id: 'onion',
    label: '양파',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'pantry',
    expirationDays: 30,
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },

  burdock: {
    id: 'burdock',
    label: '우엉',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 14,
    defaultUnitLabel: '개',
    unitOptions: ['개'],
  },

  scallion: {
    id: 'scallion',
    label: '쪽파',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 5,
    defaultUnitLabel: '단',
    unitOptions: ['단', '묶음'],
  },

  kale: {
    id: 'kale',
    label: '케일',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 5,
    defaultUnitLabel: '묶음',
    unitOptions: ['묶음', '단'],
  },

  taro: {
    id: 'taro',
    label: '토란',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'pantry',
    expirationDays: 14,
    defaultUnitLabel: '개',
    unitOptions: ['개'],
  },

  bell_pepper: {
    id: 'bell_pepper',
    label: '피망',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 7,
    defaultUnitLabel: '개',
    unitOptions: ['개'],
  },

  sweet_potato: {
    id: 'sweet_potato',
    label: '고구마',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'pantry',
    expirationDays: 30,
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },

  gosari: {
    id: 'gosari',
    label: '고사리',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 5,
    defaultUnitLabel: '묶음',
    unitOptions: ['묶음', '단'],
  },

  perilla: {
    id: 'perilla',
    label: '깻잎',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 3,
    defaultUnitLabel: '묶음',
    unitOptions: ['묶음', '단'],
  },

  carrot: {
    id: 'carrot',
    label: '당근',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 21,
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },

  doraji: {
    id: 'doraji',
    label: '도라지',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 14,
    defaultUnitLabel: '개',
    unitOptions: ['개', '묶음'],
  },

  minari: {
    id: 'minari',
    label: '미나리',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 3,
    defaultUnitLabel: '단',
    unitOptions: ['단', '묶음'],
  },

  bomdong: {
    id: 'bomdong',
    label: '봄동',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 5,
    defaultUnitLabel: '포기',
    unitOptions: ['포기', '개'],
  },

  ginger: {
    id: 'ginger',
    label: '생강',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 30,
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },

  siraegi: {
    id: 'siraegi',
    label: '시래기',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 7,
    defaultUnitLabel: '묶음',
    unitOptions: ['묶음', '단'],
  },

  crown_daisy: {
    id: 'crown_daisy',
    label: '쑥갓',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 3,
    defaultUnitLabel: '단',
    unitOptions: ['단', '묶음'],
  },

  lotus_root: {
    id: 'lotus_root',
    label: '연근',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 14,
    defaultUnitLabel: '개',
    unitOptions: ['개'],
  },

  chicory: {
    id: 'chicory',
    label: '치커리',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 4,
    defaultUnitLabel: '묶음',
    unitOptions: ['묶음', '단'],
  },

  romaine: {
    id: 'romaine',
    label: '로메인',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 4,
    defaultUnitLabel: '묶음',
    unitOptions: ['묶음', '단', '개'],
  },

  arugula: {
    id: 'arugula',
    label: '루꼴라',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 3,
    defaultUnitLabel: '묶음',
    unitOptions: ['묶음', '단'],
  },

  celery: {
    id: 'celery',
    label: '샐러리',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 10,
    defaultUnitLabel: '개',
    unitOptions: ['개', '묶음'],
  },

  spinach: {
    id: 'spinach',
    label: '시금치',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 3,
    defaultUnitLabel: '단',
    unitOptions: ['단', '묶음'],
  },

  korean_zucchini: {
    id: 'korean_zucchini',
    label: '애호박',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 7,
    defaultUnitLabel: '개',
    unitOptions: ['개'],
  },

  cabbage: {
    id: 'cabbage',
    label: '양배추',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 14,
    defaultUnitLabel: '포기',
    unitOptions: ['포기', '개'],
  },

  kohlrabi: {
    id: 'kohlrabi',
    label: '콜라비',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 14,
    defaultUnitLabel: '개',
    unitOptions: ['개'],
  },

  kabocha: {
    id: 'kabocha',
    label: '단호박',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'pantry',
    expirationDays: 30,
    defaultUnitLabel: '개',
    unitOptions: ['개'],
  },

  garlic_scape: {
    id: 'garlic_scape',
    label: '마늘쫑',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 5,
    defaultUnitLabel: '묶음',
    unitOptions: ['묶음', '단'],
  },

  lettuce: {
    id: 'lettuce',
    label: '양상추',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 7, // (기존 5에서 보수적으로 +2) 통상 머리채소가 잎채소보다 조금 김
    defaultUnitLabel: '개',
    unitOptions: ['개'],
  },

  eolgari: {
    id: 'eolgari',
    label: '얼갈이',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 4,
    defaultUnitLabel: '포기',
    unitOptions: ['포기', '묶음'],
  },

  red_chard: {
    id: 'red_chard',
    label: '적근대',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 4,
    defaultUnitLabel: '묶음',
    unitOptions: ['묶음', '단'],
  },

  red_onion: {
    id: 'red_onion',
    label: '적양파',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'pantry',
    expirationDays: 30,
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },

  chamnamul: {
    id: 'chamnamul',
    label: '참나물',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 3,
    defaultUnitLabel: '묶음',
    unitOptions: ['묶음', '단'],
  },

  bok_choy: {
    id: 'bok_choy',
    label: '청경채',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 4,
    defaultUnitLabel: '묶음',
    unitOptions: ['묶음', '단', '개'],
  },

  kongnamul: {
    id: 'kongnamul',
    label: '콩나물',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 3,
    defaultUnitLabel: '팩',
    unitOptions: ['팩', '봉'],
  },

  broccoli: {
    id: 'broccoli',
    label: '브로콜리',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 7,
    defaultUnitLabel: '개',
    unitOptions: ['개'],
  },

  shiitake: {
    id: 'shiitake',
    label: '표고버섯',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 7,
    defaultUnitLabel: '팩',
    unitOptions: ['팩', '봉'],
  },

  wood_ear: {
    id: 'wood_ear',
    label: '목이버섯',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 7,
    defaultUnitLabel: '팩',
    unitOptions: ['팩', '봉'],
  },

  sebalnamul: {
    id: 'sebalnamul',
    label: '세발나물',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 3,
    defaultUnitLabel: '묶음',
    unitOptions: ['묶음', '단'],
  },

  mung_sprout: {
    id: 'mung_sprout',
    label: '숙주나물',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 3,
    defaultUnitLabel: '팩',
    unitOptions: ['팩', '봉'],
  },

  red_cabbage: {
    id: 'red_cabbage',
    label: '적양배추',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 14,
    defaultUnitLabel: '포기',
    unitOptions: ['포기', '개'],
  },

  cheongyang_chili: {
    id: 'cheongyang_chili',
    label: '청양고추',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 10, // (기존 7 → 고추류는 상대적으로 더 가는 편)
    defaultUnitLabel: '개',
    unitOptions: ['개', '봉'],
  },

  enoki: {
    id: 'enoki',
    label: '팽이버섯',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 5,
    defaultUnitLabel: '팩',
    unitOptions: ['팩', '봉'],
  },

  oyster_mushroom: {
    id: 'oyster_mushroom',
    label: '느타리버섯',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 5,
    defaultUnitLabel: '팩',
    unitOptions: ['팩', '봉'],
  },

  king_oyster: {
    id: 'king_oyster',
    label: '새송이버섯',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 7,
    defaultUnitLabel: '팩',
    unitOptions: ['팩', '봉'],
  },

  salad_mix: {
    id: 'salad_mix',
    label: '샐러드믹스',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 3,
    defaultUnitLabel: '팩',
    unitOptions: ['팩', '봉'],
  },

  asparagus: {
    id: 'asparagus',
    label: '아스파라거스',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 5,
    defaultUnitLabel: '묶음',
    unitOptions: ['묶음', '단', '개'],
  },

  yellow_paprika: {
    id: 'yellow_paprika',
    label: '노란파프리카',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 7,
    defaultUnitLabel: '개',
    unitOptions: ['개'],
  },

  beech_mushroom: {
    id: 'beech_mushroom',
    label: '만가닥버섯',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 5,
    defaultUnitLabel: '팩',
    unitOptions: ['팩', '봉'],
  },

  brussels: {
    id: 'brussels',
    label: '방울양배추',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 7,
    defaultUnitLabel: '팩',
    unitOptions: ['팩', '봉'],
  },

  button_mushroom: {
    id: 'button_mushroom',
    label: '양송이버섯',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 5,
    defaultUnitLabel: '팩',
    unitOptions: ['팩', '봉'],
  },

  red_pepper: {
    id: 'red_pepper',
    label: '빨간파프리카',
    isActive: true,
    categories: ['vegetable'],
    defaultStorage: 'fridge',
    expirationDays: 7,
    defaultUnitLabel: '개',
    unitOptions: ['개'],
  },
} as const;

const fruitObj = {
  apple_mango: {
    id: 'apple_mango',
    label: '애플망고',
    isActive: true,
    categories: ['fruit'],
    defaultStorage: 'fridge',
    expirationDays: 5,
    defaultUnitLabel: '개',
    unitOptions: ['개'],
  },

  orange: {
    id: 'orange',
    label: '오렌지',
    isActive: true,
    categories: ['fruit'],
    defaultStorage: 'fridge',
    expirationDays: 21, // 기존 14 -> 통상 더 감
    defaultUnitLabel: '알',
    unitOptions: ['알', '상자'],
  },

  dried_mango: {
    id: 'dried_mango',
    label: '건망고',
    isActive: true,
    categories: ['fruit'],
    defaultStorage: 'pantry',
    expirationDays: 180,
    defaultUnitLabel: '봉',
    unitOptions: ['봉', '팩'],
  },

  kiwi: {
    id: 'kiwi',
    label: '키위',
    isActive: true,
    categories: ['fruit'],
    defaultStorage: 'fridge',
    expirationDays: 14, // 기존 10 -> 숙성 과일이라 냉장 보관 시 조금 더
    defaultUnitLabel: '개',
    unitOptions: ['개', '알'],
  },

  chamoe: {
    id: 'chamoe',
    label: '참외',
    isActive: true,
    categories: ['fruit'],
    defaultStorage: 'fridge',
    expirationDays: 7,
    defaultUnitLabel: '개',
    unitOptions: ['개'],
  },

  banana: {
    id: 'banana',
    label: '바나나',
    isActive: true,
    categories: ['fruit'],
    defaultStorage: 'pantry', // 숙성 전
    expirationDays: 5,
    defaultUnitLabel: '송이',
    unitOptions: ['송이', '개'],
  },

  tangerine: {
    id: 'tangerine',
    label: '귤',
    isActive: true,
    categories: ['fruit'],
    defaultStorage: 'fridge',
    expirationDays: 14,
    defaultUnitLabel: '알',
    unitOptions: ['알', '상자'],
  },

  hallabong: {
    id: 'hallabong',
    label: '한라봉',
    isActive: true,
    categories: ['fruit'],
    defaultStorage: 'fridge',
    expirationDays: 14,
    defaultUnitLabel: '알',
    unitOptions: ['알', '상자'],
  },

  watermelon: {
    id: 'watermelon',
    label: '수박',
    isActive: true,
    categories: ['fruit'],
    defaultStorage: 'fridge',
    expirationDays: 7,
    defaultUnitLabel: '개',
    unitOptions: ['개'],
  },

  peach: {
    id: 'peach',
    label: '복숭아',
    isActive: true,
    categories: ['fruit'],
    defaultStorage: 'fridge',
    expirationDays: 5,
    defaultUnitLabel: '개',
    unitOptions: ['개', '알'],
  },

  grape: {
    id: 'grape',
    label: '포도',
    isActive: true,
    categories: ['fruit'],
    defaultStorage: 'fridge',
    expirationDays: 7,
    defaultUnitLabel: '송이',
    unitOptions: ['송이', '상자'],
  },

  ginkgo_nut: {
    id: 'ginkgo_nut',
    label: '은행',
    isActive: true,
    categories: ['fruit'],
    defaultStorage: 'fridge',
    expirationDays: 14, // 기존 7 -> 손질/보관 따라 차이 크지만 기본값은 2주가 더 현실적
    defaultUnitLabel: '봉',
    unitOptions: ['봉', '팩'],
  },

  fig: {
    id: 'fig',
    label: '무화과',
    isActive: true,
    categories: ['fruit'],
    defaultStorage: 'fridge',
    expirationDays: 3, // 매우 빨리 무름
    defaultUnitLabel: '개',
    unitOptions: ['개'],
  },

  plum: {
    id: 'plum',
    label: '자두',
    isActive: true,
    categories: ['fruit'],
    defaultStorage: 'fridge',
    expirationDays: 5,
    defaultUnitLabel: '개',
    unitOptions: ['개', '알'],
  },

  cherry_tomato: {
    id: 'cherry_tomato',
    label: '방울토마토',
    isActive: true,
    categories: ['fruit'],
    defaultStorage: 'fridge',
    expirationDays: 7,
    defaultUnitLabel: '팩',
    unitOptions: ['팩', '봉'],
  },

  cashew: {
    id: 'cashew',
    label: '캐슈넛',
    isActive: true,
    categories: ['fruit'],
    defaultStorage: 'pantry',
    expirationDays: 180,
    defaultUnitLabel: '봉',
    unitOptions: ['봉', '통'],
  },

  tomato: {
    id: 'tomato',
    label: '토마토',
    isActive: true,
    categories: ['fruit'],
    defaultStorage: 'fridge',
    expirationDays: 7,
    defaultUnitLabel: '개',
    unitOptions: ['개', '알'],
  },

  shine_muscat: {
    id: 'shine_muscat',
    label: '샤인머스캣',
    isActive: true,
    categories: ['fruit'],
    defaultStorage: 'fridge',
    expirationDays: 7, // 기존 10 -> 포도류는 1주가 더 보수적
    defaultUnitLabel: '송이',
    unitOptions: ['송이', '상자'],
  },

  lemon: {
    id: 'lemon',
    label: '레몬',
    isActive: true,
    categories: ['fruit'],
    defaultStorage: 'fridge',
    expirationDays: 21,
    defaultUnitLabel: '개',
    unitOptions: ['개', '알'],
  },

  lime: {
    id: 'lime',
    label: '라임',
    isActive: true,
    categories: ['fruit'],
    defaultStorage: 'fridge',
    expirationDays: 21, // 기존 14 -> 레몬과 유사하게
    defaultUnitLabel: '개',
    unitOptions: ['개', '알'],
  },

  avocado: {
    id: 'avocado',
    label: '아보카도',
    isActive: true,
    categories: ['fruit'],
    defaultStorage: 'pantry', // 숙성 전
    expirationDays: 5,
    defaultUnitLabel: '개',
    unitOptions: ['개'],
  },

  blueberry: {
    id: 'blueberry',
    label: '블루베리',
    isActive: true,
    categories: ['fruit'],
    defaultStorage: 'fridge',
    expirationDays: 5,
    defaultUnitLabel: '팩',
    unitOptions: ['팩', '봉'],
  },

  pear: {
    id: 'pear',
    label: '배',
    isActive: true,
    categories: ['fruit'],
    defaultStorage: 'fridge',
    expirationDays: 21,
    defaultUnitLabel: '개',
    unitOptions: ['개', '알', '상자'],
  },

  almond: {
    id: 'almond',
    label: '아몬드',
    isActive: true,
    categories: ['fruit'],
    defaultStorage: 'pantry',
    expirationDays: 180,
    defaultUnitLabel: '봉',
    unitOptions: ['봉', '통'],
  },

  raisin: {
    id: 'raisin',
    label: '건포도',
    isActive: true,
    categories: ['fruit'],
    defaultStorage: 'pantry',
    expirationDays: 365,
    defaultUnitLabel: '봉',
    unitOptions: ['봉', '팩'],
  },

  strawberry: {
    id: 'strawberry',
    label: '딸기',
    isActive: true,
    categories: ['fruit'],
    defaultStorage: 'fridge',
    expirationDays: 3,
    defaultUnitLabel: '팩',
    unitOptions: ['팩', '봉'],
  },

  grapefruit: {
    id: 'grapefruit',
    label: '자몽',
    isActive: true,
    categories: ['fruit'],
    defaultStorage: 'fridge',
    expirationDays: 21, // 기존 14 -> 감귤류 중 비교적 오래감
    defaultUnitLabel: '개',
    unitOptions: ['개', '알'],
  },

  sunflower_seed: {
    id: 'sunflower_seed',
    label: '해바라기씨',
    isActive: true,
    categories: ['fruit'],
    defaultStorage: 'pantry',
    expirationDays: 180,
    defaultUnitLabel: '봉',
    unitOptions: ['봉', '통'],
  },

  pine_nut: {
    id: 'pine_nut',
    label: '잣',
    isActive: true,
    categories: ['fruit'],
    defaultStorage: 'pantry',
    expirationDays: 180, // 기존 90 -> 견과류로 묶으면 6개월 기본이 더 현실적(보수)
    defaultUnitLabel: '봉',
    unitOptions: ['봉', '통'],
  },

  macadamia: {
    id: 'macadamia',
    label: '마카다미아',
    isActive: true,
    categories: ['fruit'],
    defaultStorage: 'pantry',
    expirationDays: 180,
    defaultUnitLabel: '봉',
    unitOptions: ['봉', '통'],
  },

  pistachio: {
    id: 'pistachio',
    label: '피스타치오',
    isActive: true,
    categories: ['fruit'],
    defaultStorage: 'pantry',
    expirationDays: 180,
    defaultUnitLabel: '봉',
    unitOptions: ['봉', '통'],
  },

  pineapple: {
    id: 'pineapple',
    label: '파인애플',
    isActive: true,
    categories: ['fruit'],
    defaultStorage: 'fridge',
    expirationDays: 7,
    defaultUnitLabel: '개',
    unitOptions: ['개'],
  },

  cherry: {
    id: 'cherry',
    label: '체리',
    isActive: true,
    categories: ['fruit'],
    defaultStorage: 'fridge',
    expirationDays: 5,
    defaultUnitLabel: '팩',
    unitOptions: ['팩', '봉'],
  },

  persimmon: {
    id: 'persimmon',
    label: '단감',
    isActive: true,
    categories: ['fruit'],
    defaultStorage: 'fridge',
    expirationDays: 14,
    defaultUnitLabel: '개',
    unitOptions: ['개', '알'],
  },

  walnut: {
    id: 'walnut',
    label: '호두',
    isActive: true,
    categories: ['fruit'],
    defaultStorage: 'pantry',
    expirationDays: 180,
    defaultUnitLabel: '봉',
    unitOptions: ['봉', '통'],
  },

  pomegranate: {
    id: 'pomegranate',
    label: '석류',
    isActive: true,
    categories: ['fruit'],
    defaultStorage: 'fridge',
    expirationDays: 14,
    defaultUnitLabel: '개',
    unitOptions: ['개'],
  },

  melon: {
    id: 'melon',
    label: '멜론',
    isActive: true,
    categories: ['fruit'],
    defaultStorage: 'fridge',
    expirationDays: 7,
    defaultUnitLabel: '개',
    unitOptions: ['개'],
  },

  pumpkin_seed: {
    id: 'pumpkin_seed',
    label: '호박씨',
    isActive: true,
    categories: ['fruit'],
    defaultStorage: 'pantry',
    expirationDays: 180,
    defaultUnitLabel: '봉',
    unitOptions: ['봉', '통'],
  },

  hazelnut: {
    id: 'hazelnut',
    label: '헤이즐넛',
    isActive: true,
    categories: ['fruit'],
    defaultStorage: 'pantry',
    expirationDays: 180,
    defaultUnitLabel: '봉',
    unitOptions: ['봉', '통'],
  },

  green_apple: {
    id: 'green_apple',
    label: '초록사과',
    isActive: true,
    categories: ['fruit'],
    defaultStorage: 'fridge',
    expirationDays: 30,
    defaultUnitLabel: '개',
    unitOptions: ['개', '알', '상자'],
  },

  peanut: {
    id: 'peanut',
    label: '땅콩',
    isActive: true,
    categories: ['fruit'],
    defaultStorage: 'pantry',
    expirationDays: 180,
    defaultUnitLabel: '봉',
    unitOptions: ['봉', '통'],
  },

  red_apple: {
    id: 'red_apple',
    label: '빨간사과',
    isActive: true,
    categories: ['fruit'],
    defaultStorage: 'fridge',
    expirationDays: 30,
    defaultUnitLabel: '개',
    unitOptions: ['개', '알', '상자'],
  },

  brazil_nut: {
    id: 'brazil_nut',
    label: '브라질너트',
    isActive: true,
    categories: ['fruit'],
    defaultStorage: 'pantry',
    expirationDays: 180,
    defaultUnitLabel: '봉',
    unitOptions: ['봉', '통'],
  },

  pecan: {
    id: 'pecan',
    label: '피칸',
    isActive: true,
    categories: ['fruit'],
    defaultStorage: 'pantry',
    expirationDays: 180,
    defaultUnitLabel: '봉',
    unitOptions: ['봉', '통'],
  },

  chia_seed: {
    id: 'chia_seed',
    label: '치아씨드',
    isActive: true,
    categories: ['fruit'],
    defaultStorage: 'pantry',
    expirationDays: 365,
    defaultUnitLabel: '봉',
    unitOptions: ['봉', '통'],
  },
} as const;

const meatObj = {
  skirt_meat: {
    id: 'skirt_meat',
    label: '갈매기살',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 3,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: ['갈매기살'],
  },

  egg: {
    id: 'egg',
    label: '계란',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 21,
    defaultUnitLabel: '개',
    unitOptions: ['판', '개'],
    synonyms: ['달걀'],
  },

  egg_tray: {
    id: 'egg_tray',
    label: '계란판',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 21,
    defaultUnitLabel: '판',
    unitOptions: ['판', '구'],
    synonyms: ['계란', '달걀', '계란한판'],
  },

  baked_egg: {
    id: 'baked_egg',
    label: '구운계란',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 7,
    defaultUnitLabel: '구',
    unitOptions: ['구', '팩', '개'],
    synonyms: ['구운달걀'],
  },

  frozen_pork_belly: {
    id: 'frozen_pork_belly',
    label: '냉동삼겹살',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'freezer',
    expirationDays: 180,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: ['삼겹살'],
  },

  ground_meat: {
    id: 'ground_meat',
    label: '다짐육',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 2,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: ['다진고기', '간고기'],
  },

  chicken_breast: {
    id: 'chicken_breast',
    label: '닭가슴살',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 2,
    defaultUnitLabel: '팩',
    unitOptions: ['팩', '개'],
    synonyms: [],
  },

  chicken_wing: {
    id: 'chicken_wing',
    label: '닭날개',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 2,
    defaultUnitLabel: '팩',
    unitOptions: ['팩', '개'],
    synonyms: ['윙'],
  },

  chicken_leg: {
    id: 'chicken_leg',
    label: '닭다리',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 2,
    defaultUnitLabel: '팩',
    unitOptions: ['팩', '개'],
    synonyms: ['닭다리살'],
  },

  chicken_stew_cut: {
    id: 'chicken_stew_cut',
    label: '닭볶음탕용',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 2,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: ['볶음탕용', '닭볶음탕'],
  },

  chicken_tenderloin: {
    id: 'chicken_tenderloin',
    label: '닭안심살',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 2,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: ['닭안심'],
  },

  thin_pork_belly: {
    id: 'thin_pork_belly',
    label: '대패삼겹살',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 3,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: ['대패', '대패삼겹'],
  },

  pork_ribs: {
    id: 'pork_ribs',
    label: '등갈비',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 3,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: ['돼지등갈비'],
  },

  pork_loin_slice: {
    id: 'pork_loin_slice',
    label: '등심 잡채용',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 3,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: ['잡채용', '등심채'],
  },

  pork_loin_cube: {
    id: 'pork_loin_cube',
    label: '등심 카레용',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 3,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: ['카레용', '등심깍둑'],
  },

  quail_egg: {
    id: 'quail_egg',
    label: '메추리알',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 14,
    defaultUnitLabel: '팩',
    unitOptions: ['팩', '봉'],
    synonyms: ['메추리알'],
  },

  pork_neck: {
    id: 'pork_neck',
    label: '목살',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 3,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: ['돼지목살'],
  },

  soft_boiled_egg: {
    id: 'soft_boiled_egg',
    label: '반숙란',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 3,
    defaultUnitLabel: '구',
    unitOptions: ['구', '팩', '개'],
    synonyms: ['반숙계란', '반숙달걀'],
  },

  bacon: {
    id: 'bacon',
    label: '베이컨',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 14,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: [],
  },

  bulgogi_slice: {
    id: 'bulgogi_slice',
    label: '불고기용',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 3,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: ['불고기감', '불고기거리'],
  },

  vienna_sausage: {
    id: 'vienna_sausage',
    label: '비엔나소시지',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 14,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: ['비엔나'],
  },

  shank: {
    id: 'shank',
    label: '사태',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 3,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: [],
  },

  chuck_flap: {
    id: 'chuck_flap',
    label: '살치살',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 3,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: [],
  },

  pork_belly: {
    id: 'pork_belly',
    label: '삼겹살',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 3,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: [],
  },

  whole_chicken: {
    id: 'whole_chicken',
    label: '생닭',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 2,
    defaultUnitLabel: '마리',
    unitOptions: ['마리', '개'],
    synonyms: ['통닭'],
  },

  beef_short_rib: {
    id: 'beef_short_rib',
    label: '소고기 갈비살',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 3,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: ['갈비살'],
  },

  beef_soup_cut: {
    id: 'beef_soup_cut',
    label: '소고기 국거리용',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 3,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: ['국거리', '국거리용'],
  },

  beef_shabu_slice: {
    id: 'beef_shabu_slice',
    label: '샤브샤브용',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 3,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: ['샤브용'],
  },

  beef_short_slice: {
    id: 'beef_short_slice',
    label: '우삼겹살',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 3,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: ['우삼겹'],
  },

  beef_steak: {
    id: 'beef_steak',
    label: '소고기 스테이크',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 3,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: ['스테이크'],
  },

  beef_tenderloin: {
    id: 'beef_tenderloin',
    label: '소고기 안심',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 3,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: ['안심'],
  },

  beef_brisket: {
    id: 'beef_brisket',
    label: '소고기 양지',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 3,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: ['양지', '양지머리'],
  },

  beef_brisket_slice: {
    id: 'beef_brisket_slice',
    label: '소고기 차돌박이',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 3,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: ['차돌'],
  },

  boiled_pork_cut: {
    id: 'boiled_pork_cut',
    label: '수육용',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 3,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: ['수육거리', '수육감'],
  },

  diet_chicken_breast: {
    id: 'diet_chicken_breast',
    label: '식단용 닭가슴살',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 5, // 가공/포장 제품 느낌이라 기존값 유지
    defaultUnitLabel: '팩',
    unitOptions: ['팩', '개'],
    synonyms: ['닭가슴살', '닭가슴살팩'],
  },

  beef_shank_special: {
    id: 'beef_shank_special',
    label: '아롱사태',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 3,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: [],
  },

  outside_skirt: {
    id: 'outside_skirt',
    label: '안창살',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 3,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: [],
  },

  pork_shoulder_stew: {
    id: 'pork_shoulder_stew',
    label: '앞다리살 찌개',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 3,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: ['앞다리살', '찌개용'],
  },

  duck_slice: {
    id: 'duck_slice',
    label: '오리정육슬라이스',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 3,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: ['오리슬라이스', '오리고기'],
  },

  smoked_duck_slice: {
    id: 'smoked_duck_slice',
    label: '오리훈제슬라이스',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 14,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: ['훈제오리', '오리훈제'],
  },

  round_braise: {
    id: 'round_braise',
    label: '우둔 장조림용',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 3,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: ['장조림용', '우둔'],
  },

  braised_short_rib: {
    id: 'braised_short_rib',
    label: '찜갈비',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 3,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: ['갈비찜용'],
  },

  sirloin_steak: {
    id: 'sirloin_steak',
    label: '채끝 스테이크',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 3,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: ['채끝'],
  },

  jamon: {
    id: 'jamon',
    label: '하몽',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 30,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: [],
  },

  pork_jowl: {
    id: 'pork_jowl',
    label: '항정살',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 3,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: [],
  },

  tomahawk_steak: {
    id: 'tomahawk_steak',
    label: '토마호크',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 3,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: ['토마호크스테이크'],
  },

  beef_round: {
    id: 'beef_round',
    label: '홍두깨',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 3,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: ['홍두깨살'],
  },

  frank_sausage: {
    id: 'frank_sausage',
    label: '후랑크소시지',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 14,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: ['후랑크', '프랑크소시지'],
  },

  smoked_chicken_breast: {
    id: 'smoked_chicken_breast',
    label: '훈제닭가슴살',
    isActive: true,
    categories: ['meat'],
    defaultStorage: 'fridge',
    expirationDays: 14,
    defaultUnitLabel: '팩',
    unitOptions: ['팩', '개'],
    synonyms: ['훈제닭가슴', '닭가슴살'],
  },
} as const;

const dairyObj = {
  greek_yogurt: {
    id: 'greek_yogurt',
    label: '그릭요거트',
    isActive: true,
    categories: ['dairy'],
    defaultStorage: 'fridge',
    expirationDays: 14,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: ['요거트', '그릭요구르트'],
  },

  ricotta: {
    id: 'ricotta',
    label: '리코타치즈',
    isActive: true,
    categories: ['dairy'],
    defaultStorage: 'fridge',
    expirationDays: 7,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: ['리코타'],
  },

  mascarpone: {
    id: 'mascarpone',
    label: '마스카포네',
    isActive: true,
    categories: ['dairy'],
    defaultStorage: 'fridge',
    expirationDays: 7,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: ['마스카포네치즈'],
  },

  mozzarella: {
    id: 'mozzarella',
    label: '모짜렐라치즈',
    isActive: true,
    categories: ['dairy'],
    defaultStorage: 'fridge',
    expirationDays: 7,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: ['모짜렐라'],
  },

  butter: {
    id: 'butter',
    label: '버터',
    isActive: true,
    categories: ['dairy'],
    defaultStorage: 'fridge',
    expirationDays: 60, // 기존 30 -> 보수적이면서도 현실적으로는 더 감
    defaultUnitLabel: '개',
    unitOptions: ['개', '통'],
    synonyms: ['무염버터', '가염버터'],
  },

  burrata: {
    id: 'burrata',
    label: '부라타치즈',
    isActive: true,
    categories: ['dairy'],
    defaultStorage: 'fridge',
    expirationDays: 5,
    defaultUnitLabel: '팩',
    unitOptions: ['팩', '개'],
    synonyms: ['부라타'],
  },

  brie: {
    id: 'brie',
    label: '브리치즈',
    isActive: true,
    categories: ['dairy'],
    defaultStorage: 'fridge',
    expirationDays: 14,
    defaultUnitLabel: '팩',
    unitOptions: ['팩', '조각'],
    synonyms: ['브리'],
  },

  sour_cream: {
    id: 'sour_cream',
    label: '사워크림',
    isActive: true,
    categories: ['dairy'],
    defaultStorage: 'fridge',
    expirationDays: 14,
    defaultUnitLabel: '팩',
    unitOptions: ['팩', '통'],
    synonyms: ['사우어크림', '사워크림'],
  },

  fresh_cream: {
    id: 'fresh_cream',
    label: '생크림',
    isActive: true,
    categories: ['dairy'],
    defaultStorage: 'fridge',
    expirationDays: 7,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: ['헤비크림', '생크림(헤비)'],
  },

  whipping_cream: {
    id: 'whipping_cream',
    label: '휘핑크림',
    isActive: true,
    categories: ['dairy'],
    defaultStorage: 'fridge',
    expirationDays: 14,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: ['휘핑크림(액상)'],
  },

  whipped_cream_spray: {
    id: 'whipped_cream_spray',
    label: '휘핑크림 스프레이',
    isActive: true,
    categories: ['dairy'],
    defaultStorage: 'fridge',
    expirationDays: 30,
    defaultUnitLabel: '통',
    unitOptions: ['통'],
    synonyms: ['생크림스프레이', '휘핑스프레이'],
  },

  string_cheese: {
    id: 'string_cheese',
    label: '스트링치즈',
    isActive: true,
    categories: ['dairy'],
    defaultStorage: 'fridge',
    expirationDays: 21,
    defaultUnitLabel: '팩',
    unitOptions: ['팩', '개'],
    synonyms: ['스트링'],
  },

  sliced_cheese: {
    id: 'sliced_cheese',
    label: '슬라이스치즈',
    isActive: true,
    categories: ['dairy'],
    defaultStorage: 'fridge',
    expirationDays: 21,
    defaultUnitLabel: '팩',
    unitOptions: ['팩', '장'],
    synonyms: ['슬라이스', '치즈슬라이스'],
  },

  shredded_cheese: {
    id: 'shredded_cheese',
    label: '슈레드치즈',
    isActive: true,
    categories: ['dairy'],
    defaultStorage: 'fridge',
    expirationDays: 21,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: ['슈레디드치즈', '피자치즈', '모짜렐라슈레드'],
  },

  cheddar: {
    id: 'cheddar',
    label: '체다치즈',
    isActive: true,
    categories: ['dairy'],
    defaultStorage: 'fridge',
    expirationDays: 30,
    defaultUnitLabel: '팩',
    unitOptions: ['팩', '조각'],
    synonyms: ['체다'],
  },

  cheese: {
    id: 'cheese',
    label: '치즈',
    isActive: true,
    categories: ['dairy'],
    defaultStorage: 'fridge',
    expirationDays: 14,
    defaultUnitLabel: '팩',
    unitOptions: ['팩', '조각', '장'],
    synonyms: ['자연치즈', '가공치즈'],
  },

  cream_cheese: {
    id: 'cream_cheese',
    label: '크림치즈',
    isActive: true,
    categories: ['dairy'],
    defaultStorage: 'fridge',
    expirationDays: 21, // 기존 14 -> 보수적으로 3주 정도가 체감상 자연스러움
    defaultUnitLabel: '팩',
    unitOptions: ['팩', '통'],
    synonyms: ['크림치즈스프레드'],
  },

  parmesan: {
    id: 'parmesan',
    label: '파마산치즈',
    isActive: true,
    categories: ['dairy'],
    defaultStorage: 'fridge',
    expirationDays: 60, // 기존 30 -> 분말/블럭 편차 큼, 기본값은 2달이 더 실사용에 맞음
    defaultUnitLabel: '통',
    unitOptions: ['통', '팩'],
    synonyms: ['파르메산', '파마산', '파르메산치즈'],
  },

  condensed_milk: {
    id: 'condensed_milk',
    label: '연유',
    isActive: true,
    categories: ['dairy'],
    defaultStorage: 'fridge',
    expirationDays: 180,
    defaultUnitLabel: '통',
    unitOptions: ['통'],
    synonyms: ['콘덴스밀크'],
  },

  yogurt: {
    id: 'yogurt',
    label: '요거트',
    isActive: true,
    categories: ['dairy'],
    defaultStorage: 'fridge',
    expirationDays: 14,
    defaultUnitLabel: '팩',
    unitOptions: ['팩'],
    synonyms: ['요구르트', '플레인요거트'],
  },

  milk: {
    id: 'milk',
    label: '우유',
    isActive: true,
    categories: ['dairy'],
    defaultStorage: 'fridge',
    expirationDays: 7,
    defaultUnitLabel: '팩',
    unitOptions: ['팩', '병'],
    synonyms: ['우유팩', '흰우유'],
  },
} as const;

export const ingredientObj = {
  vegetable: vegetableObj,
  fruit: fruitObj,
  noodle: noodleObj,
  meat: meatObj,
  dairy: dairyObj,
  // seafood: {},
  // grains: {},
  // sidedish: {},
  // conveniencefood: {},
  // seasoning: {},
  // powder: {},
  // desert: {},
  // drink: {},
  // health: {},
  // can: {},
};

export const ingredientImagesObj: {
  [key in Category]: { [key in string]: ImageSourcePropType };
} = {
  noodle: {
    udon: require('../../assets/images/ingredients/noodle/udon.png'),
    gamja_ongsimi: require('../../assets/images/ingredients/noodle/gamja_ongsimi.png'),
    tortilla: require('../../assets/images/ingredients/noodle/tortilla.png'),
    fusilli: require('../../assets/images/ingredients/noodle/fusilli.png'),
    spaghetti_noodle: require('../../assets/images/ingredients/noodle/spaghetti_noodle.png'),
    jjolmyeon_noodle: require('../../assets/images/ingredients/noodle/jjolmyeon_noodle.png'),
    tteokbokki_ricecake: require('../../assets/images/ingredients/noodle/tteokbokki_ricecake.png'),
    penne: require('../../assets/images/ingredients/noodle/penne.png'),
    tteok_soup_ricecake: require('../../assets/images/ingredients/noodle/tteok_soup_ricecake.png'),
    sujebi: require('../../assets/images/ingredients/noodle/sujebi.png'),
    rice_noodle: require('../../assets/images/ingredients/noodle/rice_noodle.png'),
    konjac_noodle: require('../../assets/images/ingredients/noodle/konjac_noodle.png'),
    buckwheat_noodle: require('../../assets/images/ingredients/noodle/buckwheat_noodle.png'),
    dumpling_wrapper: require('../../assets/images/ingredients/noodle/dumpling_wrapper.png'),
    kalguksu_noodle: require('../../assets/images/ingredients/noodle/kalguksu_noodle.png'),
    naengmyeon: require('../../assets/images/ingredients/noodle/naengmyeon.png'),
    chinese_noodle: require('../../assets/images/ingredients/noodle/chinese_noodle.png'),
    rice_paper: require('../../assets/images/ingredients/noodle/rice_paper.png'),
    flat_glass_noodle: require('../../assets/images/ingredients/noodle/flat_glass_noodle.png'),
    glass_noodle: require('../../assets/images/ingredients/noodle/glass_noodle.png'),
  },

  vegetable: {
    radish: require('../../assets/images/ingredients/vegetable/radish.png'),
    eggplant: require('../../assets/images/ingredients/vegetable/eggplant.png'),
    green_onion: require('../../assets/images/ingredients/vegetable/green_onion.png'),
    napa: require('../../assets/images/ingredients/vegetable/napa.png'),
    chive: require('../../assets/images/ingredients/vegetable/chive.png'),
    beet: require('../../assets/images/ingredients/vegetable/beet.png'),
    cucumber: require('../../assets/images/ingredients/vegetable/cucumber.png'),
    potato: require('../../assets/images/ingredients/vegetable/potato.png'),
    chard: require('../../assets/images/ingredients/vegetable/chard.png'),
    naengi: require('../../assets/images/ingredients/vegetable/naengi.png'),
    dallae: require('../../assets/images/ingredients/vegetable/dallae.png'),
    garlic: require('../../assets/images/ingredients/vegetable/garlic.png'),
    leaf_lettuce: require('../../assets/images/ingredients/vegetable/leaf_lettuce.png'),
    onion: require('../../assets/images/ingredients/vegetable/onion.png'),
    burdock: require('../../assets/images/ingredients/vegetable/burdock.png'),
    scallion: require('../../assets/images/ingredients/vegetable/scallion.png'),
    kale: require('../../assets/images/ingredients/vegetable/kale.png'),
    taro: require('../../assets/images/ingredients/vegetable/taro.png'),
    bell_pepper: require('../../assets/images/ingredients/vegetable/bell_pepper.png'),
    sweet_potato: require('../../assets/images/ingredients/vegetable/sweet_potato.png'),
    gosari: require('../../assets/images/ingredients/vegetable/gosari.png'),
    perilla: require('../../assets/images/ingredients/vegetable/perilla.png'),
    carrot: require('../../assets/images/ingredients/vegetable/carrot.png'),
    doraji: require('../../assets/images/ingredients/vegetable/doraji.png'),
    minari: require('../../assets/images/ingredients/vegetable/minari.png'),
    bomdong: require('../../assets/images/ingredients/vegetable/bomdong.png'),
    ginger: require('../../assets/images/ingredients/vegetable/ginger.png'),
    siraegi: require('../../assets/images/ingredients/vegetable/siraegi.png'),
    crown_daisy: require('../../assets/images/ingredients/vegetable/crown_daisy.png'),
    lotus_root: require('../../assets/images/ingredients/vegetable/lotus_root.png'),
    chicory: require('../../assets/images/ingredients/vegetable/chicory.png'),
    romaine: require('../../assets/images/ingredients/vegetable/romaine.png'),
    arugula: require('../../assets/images/ingredients/vegetable/arugula.png'),
    celery: require('../../assets/images/ingredients/vegetable/celery.png'),
    spinach: require('../../assets/images/ingredients/vegetable/spinach.png'),
    korean_zucchini: require('../../assets/images/ingredients/vegetable/korean_zucchini.png'),
    cabbage: require('../../assets/images/ingredients/vegetable/cabbage.png'),
    kohlrabi: require('../../assets/images/ingredients/vegetable/kohlrabi.png'),
    kabocha: require('../../assets/images/ingredients/vegetable/kabocha.png'),
    garlic_scape: require('../../assets/images/ingredients/vegetable/garlic_scape.png'),
    lettuce: require('../../assets/images/ingredients/vegetable/lettuce.png'),
    eolgari: require('../../assets/images/ingredients/vegetable/eolgari.png'),
    red_chard: require('../../assets/images/ingredients/vegetable/red_chard.png'),
    red_onion: require('../../assets/images/ingredients/vegetable/red_onion.png'),
    chamnamul: require('../../assets/images/ingredients/vegetable/chamnamul.png'),
    bok_choy: require('../../assets/images/ingredients/vegetable/bok_choy.png'),
    kongnamul: require('../../assets/images/ingredients/vegetable/kongnamul.png'),
    broccoli: require('../../assets/images/ingredients/vegetable/broccoli.png'),
    shiitake: require('../../assets/images/ingredients/vegetable/shiitake.png'),
    wood_ear: require('../../assets/images/ingredients/vegetable/wood_ear.png'),
    sebalnamul: require('../../assets/images/ingredients/vegetable/sebalnamul.png'),
    mung_sprout: require('../../assets/images/ingredients/vegetable/mung_sprout.png'),
    red_cabbage: require('../../assets/images/ingredients/vegetable/red_cabbage.png'),
    cheongyang_chili: require('../../assets/images/ingredients/vegetable/cheongyang_chili.png'),
    enoki: require('../../assets/images/ingredients/vegetable/enoki.png'),
    oyster_mushroom: require('../../assets/images/ingredients/vegetable/oyster_mushroom.png'),
    king_oyster: require('../../assets/images/ingredients/vegetable/king_oyster.png'),
    salad_mix: require('../../assets/images/ingredients/vegetable/salad_mix.png'),
    asparagus: require('../../assets/images/ingredients/vegetable/asparagus.png'),
    yellow_paprika: require('../../assets/images/ingredients/vegetable/yellow_paprika.png'),
    beech_mushroom: require('../../assets/images/ingredients/vegetable/beech_mushroom.png'),
    brussels: require('../../assets/images/ingredients/vegetable/brussels.png'),
    button_mushroom: require('../../assets/images/ingredients/vegetable/button_mushroom.png'),
    red_pepper: require('../../assets/images/ingredients/vegetable/red_pepper.png'),
  },

  fruit: {
    apple_mango: require('../../assets/images/ingredients/fruit/apple_mango.png'),
    orange: require('../../assets/images/ingredients/fruit/orange.png'),
    dried_mango: require('../../assets/images/ingredients/fruit/dried_mango.png'),
    kiwi: require('../../assets/images/ingredients/fruit/kiwi.png'),
    chamoe: require('../../assets/images/ingredients/fruit/chamoe.png'),
    banana: require('../../assets/images/ingredients/fruit/banana.png'),
    tangerine: require('../../assets/images/ingredients/fruit/tangerine.png'),
    hallabong: require('../../assets/images/ingredients/fruit/hallabong.png'),
    watermelon: require('../../assets/images/ingredients/fruit/watermelon.png'),
    peach: require('../../assets/images/ingredients/fruit/peach.png'),
    grape: require('../../assets/images/ingredients/fruit/grape.png'),
    ginkgo_nut: require('../../assets/images/ingredients/fruit/ginkgo_nut.png'),
    fig: require('../../assets/images/ingredients/fruit/fig.png'),
    plum: require('../../assets/images/ingredients/fruit/plum.png'),
    cherry_tomato: require('../../assets/images/ingredients/fruit/cherry_tomato.png'),
    cashew: require('../../assets/images/ingredients/fruit/cashew.png'),
    tomato: require('../../assets/images/ingredients/fruit/tomato.png'),
    shine_muscat: require('../../assets/images/ingredients/fruit/shine_muscat.png'),
    lemon: require('../../assets/images/ingredients/fruit/lemon.png'),
    lime: require('../../assets/images/ingredients/fruit/lime.png'),
    avocado: require('../../assets/images/ingredients/fruit/avocado.png'),
    blueberry: require('../../assets/images/ingredients/fruit/blueberry.png'),
    pear: require('../../assets/images/ingredients/fruit/pear.png'),
    almond: require('../../assets/images/ingredients/fruit/almond.png'),
    raisin: require('../../assets/images/ingredients/fruit/raisin.png'),
    strawberry: require('../../assets/images/ingredients/fruit/strawberry.png'),
    grapefruit: require('../../assets/images/ingredients/fruit/grapefruit.png'),
    sunflower_seed: require('../../assets/images/ingredients/fruit/sunflower_seed.png'),
    pine_nut: require('../../assets/images/ingredients/fruit/pine_nut.png'),
    macadamia: require('../../assets/images/ingredients/fruit/macadamia.png'),
    pistachio: require('../../assets/images/ingredients/fruit/pistachio.png'),
    pineapple: require('../../assets/images/ingredients/fruit/pineapple.png'),
    cherry: require('../../assets/images/ingredients/fruit/cherry.png'),
    persimmon: require('../../assets/images/ingredients/fruit/persimmon.png'),
    walnut: require('../../assets/images/ingredients/fruit/walnut.png'),
    pomegranate: require('../../assets/images/ingredients/fruit/pomegranate.png'),
    melon: require('../../assets/images/ingredients/fruit/melon.png'),
    pumpkin_seed: require('../../assets/images/ingredients/fruit/pumpkin_seed.png'),
    hazelnut: require('../../assets/images/ingredients/fruit/hazelnut.png'),
    green_apple: require('../../assets/images/ingredients/fruit/green_apple.png'),
    peanut: require('../../assets/images/ingredients/fruit/peanut.png'),
    apple: require('../../assets/images/ingredients/fruit/apple.png'),
    brazil_nut: require('../../assets/images/ingredients/fruit/brazil_nut.png'),
    pecan: require('../../assets/images/ingredients/fruit/pecan.png'),
    chia_seed: require('../../assets/images/ingredients/fruit/chia_seed.png'),
  },

  seafood: {},

  meat: {
    //갈매기살
    skirt_meat: require('../../assets/images/ingredients/meat/skirt_meat.png'),
    //계란
    egg: require('../../assets/images/ingredients/meat/egg.png'),
    //계란판
    egg_tray: require('../../assets/images/ingredients/meat/egg_tray.png'),
    //구운계란
    baked_egg: require('../../assets/images/ingredients/meat/baked_egg.png'),
    //냉동삼겹살
    frozen_pork_belly: require('../../assets/images/ingredients/meat/frozen_pork_belly.png'),
    //다짐육
    ground_meat: require('../../assets/images/ingredients/meat/ground_meat.png'),
    //닭가슴살
    chicken_breast: require('../../assets/images/ingredients/meat/chicken_breast.png'),
    //닭날개
    chicken_wing: require('../../assets/images/ingredients/meat/chicken_wing.png'),
    //닭다리
    chicken_leg: require('../../assets/images/ingredients/meat/chicken_leg.png'),
    //닭볶음탕용
    chicken_stew_cut: require('../../assets/images/ingredients/meat/chicken_stew_cut.png'),
    //닭안심살
    chicken_tenderloin: require('../../assets/images/ingredients/meat/chicken_tenderloin.png'),
    //대패삼겹살
    thin_pork_belly: require('../../assets/images/ingredients/meat/thin_sliced_meat.png'),
    //등갈비
    pork_ribs: require('../../assets/images/ingredients/meat/pork_ribs.png'),
    //등심 잡채용
    pork_loin_slice: require('../../assets/images/ingredients/meat/pork_loin_slice.png'),
    //등심 카레용
    pork_loin_cube: require('../../assets/images/ingredients/meat/pork_loin_cube.png'),
    //메추리알
    quail_egg: require('../../assets/images/ingredients/meat/quail_egg.png'),
    //목살
    pork_neck: require('../../assets/images/ingredients/meat/pork_neck.png'),
    //반숙란
    soft_boiled_egg: require('../../assets/images/ingredients/meat/soft_boiled_egg.png'),
    //베이컨
    bacon: require('../../assets/images/ingredients/meat/thin_sliced_meat.png'),
    //불고기용
    bulgogi_slice: require('../../assets/images/ingredients/meat/bulgogi_slice.png'),
    //비엔나소시지
    vienna_sausage: require('../../assets/images/ingredients/meat/sausage.png'),
    //사태
    shank: require('../../assets/images/ingredients/meat/shank.png'),
    //살치살
    chuck_flap: require('../../assets/images/ingredients/meat/roast_slice.png'),
    //삼겹살
    pork_belly: require('../../assets/images/ingredients/meat/boiled_meat.png'),
    //생닭
    whole_chicken: require('../../assets/images/ingredients/meat/whole_chicken.png'),
    //소고기 갈비살
    beef_short_rib: require('../../assets/images/ingredients/meat/roast_slice.png'),
    //소고기 국거리용
    beef_soup_cut: require('../../assets/images/ingredients/meat/soup_cut.png'),
    //소고기 샤브샤브용
    beef_shabu_slice: require('../../assets/images/ingredients/meat/shabu_slice.png'),
    //소고기 스테이크
    beef_steak: require('../../assets/images/ingredients/meat/steak.png'),
    //소고기 안심
    beef_tenderloin: require('../../assets/images/ingredients/meat/beef_tenderloin.png'),
    //소고기 양지
    beef_brisket: require('../../assets/images/ingredients/meat/beef_brisket.png'),
    //소고기 차돌박이
    beef_brisket_slice: require('../../assets/images/ingredients/meat/shabu_slice.png'),
    // 우삼겹살
    beef_short_slice: require('../../assets/images/ingredients/meat/shabu_slice.png'),
    //수육용
    boiled_pork_cut: require('../../assets/images/ingredients/meat/boiled_meat.png'),
    //식단용 닭가슴살
    diet_chicken_breast: require('../../assets/images/ingredients/meat/diet_chicken_breast.png'),
    //아롱사태
    beef_shank_special: require('../../assets/images/ingredients/meat/shank.png'),
    //안창살
    outside_skirt: require('../../assets/images/ingredients/meat/roast_slice.png'),
    //앞다리살 찌개
    pork_shoulder_stew: require('../../assets/images/ingredients/meat/soup_cut.png'),
    //오리정육슬라이스
    duck_slice: require('../../assets/images/ingredients/meat/duck_slice.png'),
    //오리훈제슬라이스
    smoked_duck_slice: require('../../assets/images/ingredients/meat/smoked_duck_slice.png'),
    //우둔 장조림용
    round_braise: require('../../assets/images/ingredients/meat/round_braise.png'),
    //찜갈비
    braised_short_rib: require('../../assets/images/ingredients/meat/braised_short_rib.png'),
    //채끝 스테이크
    sirloin_steak: require('../../assets/images/ingredients/meat/steak.png'),
    //하몽
    jamon: require('../../assets/images/ingredients/meat/jamon.png'),
    //항정살
    pork_jowl: require('../../assets/images/ingredients/meat/pork_jowl.png'),
    //호마토크
    tomahawk_steak: require('../../assets/images/ingredients/meat/tomahawk_steak.png'),
    //홍두깨
    beef_round: require('../../assets/images/ingredients/meat/beef_round.png'),
    //후랑크소시지
    frank_sausage: require('../../assets/images/ingredients/meat/sausage.png'),
    //훈제닭가슴살
    smoked_chicken_breast: require('../../assets/images/ingredients/meat/smoked_chicken_breast.png'),
  },

  seasoning: {
    tomato_sauce: require('../../assets/images/ingredients/sauce/tomato_sauce.png'),
  },

  dairy: {
    greek_yogurt: require('../../assets/images/ingredients/dairy/greek_yogurt.png'),
    ricotta: require('../../assets/images/ingredients/dairy/ricotta.png'),
    mascarpone: require('../../assets/images/ingredients/dairy/mascarpone.png'),
    mozzarella: require('../../assets/images/ingredients/dairy/mozzarella.png'),
    butter: require('../../assets/images/ingredients/dairy/butter.png'),
    burrata: require('../../assets/images/ingredients/dairy/burrata.png'),
    brie: require('../../assets/images/ingredients/dairy/brie.png'),
    sour_cream: require('../../assets/images/ingredients/dairy/sour_cream.png'),
    fresh_cream: require('../../assets/images/ingredients/dairy/fresh_cream.png'),
    string_cheese: require('../../assets/images/ingredients/dairy/string_cheese.png'),
    sliced_cheese: require('../../assets/images/ingredients/dairy/sliced_cheese.png'),
    shredded_cheese: require('../../assets/images/ingredients/dairy/shredded_cheese.png'),
    condensed_milk: require('../../assets/images/ingredients/dairy/condensed_milk.png'),
    yogurt: require('../../assets/images/ingredients/dairy/yogurt.png'),
    milk: require('../../assets/images/ingredients/dairy/milk.png'),
    cheddar: require('../../assets/images/ingredients/dairy/cheddar.png'),
    cheese: require('../../assets/images/ingredients/dairy/cheese.png'),
    cream_cheese: require('../../assets/images/ingredients/dairy/cream_cheese.png'),
    parmesan: require('../../assets/images/ingredients/dairy/parmesan.png'),
    whipping_cream: require('../../assets/images/ingredients/dairy/whipping_cream.png'),
    whipped_cream_spray: require('../../assets/images/ingredients/dairy/whipped_cream_spray.png'),
  },

  grains: {},

  sidedish: {},
  conveniencefood: {},

  powder: {},
  desert: {},
  drink: {},
  health: {},
  can: {},
} as const;
