const noodleObj = {
  udon: {
    label: '우동',
    name: 'udon',
    category: 'noodle',
    icon: '',
    defaultStorage: '실온',
    tags: ['면', '밀가루'],
    expirationDate: 180,
    synonyms: ['우동면'],
  },

  gamja_ongsimi: {
    label: '감자옹심이',
    name: 'gamja_ongsimi',
    category: 'noodle',
    icon: '',
    defaultStorage: '실온',
    tags: ['감자', '떡'],
    expirationDate: 120,
    synonyms: [],
  },

  tortilla: {
    label: '또띠아',
    name: 'tortilla',
    category: 'noodle',
    icon: '',
    defaultStorage: '실온',
    tags: ['밀가루', '랩'],
    expirationDate: 90,
    synonyms: ['토르티야'],
  },

  fusilli: {
    label: '푸실리',
    name: 'fusilli',
    category: 'noodle',
    icon: '',
    defaultStorage: '실온',
    tags: ['파스타'],
    expirationDate: 730,
    synonyms: [],
  },

  spaghetti: {
    label: '스파게티면',
    name: 'spaghetti',
    category: 'noodle',
    icon: '',
    defaultStorage: '실온',
    tags: ['파스타', '건면'],
    expirationDate: 730,
    synonyms: ['스파게티'],
  },

  tteokbokki_ricecake: {
    label: '떡볶이떡',
    name: 'tteokbokki_ricecake',
    category: 'noodle',
    icon: '',
    defaultStorage: '실온',
    tags: ['쌀', '떡'],
    expirationDate: 90,
    synonyms: [],
  },

  penne: {
    label: '펜네',
    name: 'penne',
    category: 'noodle',
    icon: '',
    defaultStorage: '실온',
    tags: ['파스타'],
    expirationDate: 730,
    synonyms: [],
  },

  tteok_soup_ricecake: {
    label: '떡국떡',
    name: 'tteok_soup_ricecake',
    category: 'noodle',
    icon: '',
    defaultStorage: '실온',
    tags: ['쌀', '떡'],
    expirationDate: 60,
    synonyms: [],
  },

  sujebi: {
    label: '수제비',
    name: 'sujebi',
    category: 'noodle',
    icon: '',
    defaultStorage: '실온',
    tags: ['밀가루'],
    expirationDate: 120,
    synonyms: [],
  },

  rice_noodle: {
    label: '쌀국수면',
    name: 'rice_noodle',
    category: 'noodle',
    icon: '',
    defaultStorage: '실온',
    tags: ['쌀', '건면'],
    expirationDate: 365,
    synonyms: ['포면'],
  },

  konjac_noodle: {
    label: '곤약면',
    name: 'konjac_noodle',
    category: 'noodle',
    icon: '',
    defaultStorage: '실온',
    tags: ['저칼로리'],
    expirationDate: 365,
    synonyms: [],
  },

  buckwheat_noodle: {
    label: '메밀면',
    name: 'buckwheat_noodle',
    category: 'noodle',
    icon: '',
    defaultStorage: '실온',
    tags: ['메밀'],
    expirationDate: 365,
    synonyms: [],
  },

  dumpling_wrapper: {
    label: '만두피',
    name: 'dumpling_wrapper',
    category: 'noodle',
    icon: '',
    defaultStorage: '실온',
    tags: ['밀가루'],
    expirationDate: 90,
    synonyms: [],
  },

  kalguksu_noodle: {
    label: '칼국수면',
    name: 'kalguksu_noodle',
    category: 'noodle',
    icon: '',
    defaultStorage: '실온',
    tags: ['국수'],
    expirationDate: 120,
    synonyms: [],
  },

  naengmyeon: {
    label: '냉면',
    name: 'naengmyeon',
    category: 'noodle',
    icon: '',
    defaultStorage: '실온',
    tags: ['국수'],
    expirationDate: 120,
    synonyms: [],
  },

  chinese_noodle: {
    label: '중화면',
    name: 'chinese_noodle',
    category: 'noodle',
    icon: '',
    defaultStorage: '실온',
    tags: ['중식'],
    expirationDate: 180,
    synonyms: [],
  },

  rice_paper: {
    label: '라이스페이퍼',
    name: 'rice_paper',
    category: 'noodle',
    icon: '',
    defaultStorage: '실온',
    tags: ['쌀'],
    expirationDate: 365,
    synonyms: [],
  },

  flat_glass_noodle: {
    label: '납작당면',
    name: 'flat_glass_noodle',
    category: 'noodle',
    icon: '',
    defaultStorage: '실온',
    tags: ['당면'],
    expirationDate: 730,
    synonyms: ['중국당면'],
  },
} as const;

const vegetableObj = {
  radish: {
    name: 'radish',
    label: '무',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 14,
  },
  eggplant: {
    name: 'eggplant',
    label: '가지',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 5,
  },
  green_onion: {
    name: 'green_onion',
    label: '대파',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 7,
  },
  napa: {
    name: 'napa',
    label: '배추',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 10,
  },
  chive: {
    name: 'chive',
    label: '부추',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 4,
  },
  beet: {
    name: 'beet',
    label: '비트',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 14,
  },
  cucumber: {
    name: 'cucumber',
    label: '오이',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 5,
  },
  potato: {
    name: 'potato',
    label: '감자',
    category: 'vegetable',
    icon: '',
    defaultStorage: '실온',
    expirationDate: 30,
  },
  chard: {
    name: 'chard',
    label: '근대',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 4,
  },
  naengi: {
    name: 'naengi',
    label: '냉이',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 3,
  },
  dallae: {
    name: 'dallae',
    label: '달래',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 3,
  },
  garlic: {
    name: 'garlic',
    label: '마늘',
    category: 'vegetable',
    icon: '',
    defaultStorage: '실온',
    expirationDate: 60,
  },
  leaf_lettuce: {
    name: 'leaf_lettuce',
    label: '상추',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 3,
  },
  onion: {
    name: 'onion',
    label: '양파',
    category: 'vegetable',
    icon: '',
    defaultStorage: '실온',
    expirationDate: 30,
  },
  burdock: {
    name: 'burdock',
    label: '우엉',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 14,
  },
  scallion: {
    name: 'scallion',
    label: '쪽파',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 5,
  },
  kale: {
    name: 'kale',
    label: '케일',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 5,
  },
  taro: {
    name: 'taro',
    label: '토란',
    category: 'vegetable',
    icon: '',
    defaultStorage: '실온',
    expirationDate: 14,
  },
  bell_pepper: {
    name: 'bell_pepper',
    label: '피망',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 7,
  },
  sweet_potato: {
    name: 'sweet_potato',
    label: '고구마',
    category: 'vegetable',
    icon: '',
    defaultStorage: '실온',
    expirationDate: 30,
  },
  gosari: {
    name: 'gosari',
    label: '고사리',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 5,
  },
  perilla: {
    name: 'perilla',
    label: '깻잎',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 3,
  },
  carrot: {
    name: 'carrot',
    label: '당근',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 21,
  },
  doraji: {
    name: 'doraji',
    label: '도라지',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 14,
  },
  minari: {
    name: 'minari',
    label: '미나리',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 3,
  },
  bomdong: {
    name: 'bomdong',
    label: '봄동',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 5,
  },
  ginger: {
    name: 'ginger',
    label: '생강',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 30,
  },
  siraegi: {
    name: 'siraegi',
    label: '시래기',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 7,
  },
  crown_daisy: {
    name: 'crown_daisy',
    label: '쑥갓',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 3,
  },
  lotus_root: {
    name: 'lotus_root',
    label: '연근',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 14,
  },
  chicory: {
    name: 'chicory',
    label: '치커리',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 4,
  },
  romaine: {
    name: 'romaine',
    label: '로메인',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 4,
  },
  arugula: {
    name: 'arugula',
    label: '루꼴라',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 3,
  },
  celery: {
    name: 'celery',
    label: '샐러리',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 10,
  },
  spinach: {
    name: 'spinach',
    label: '시금치',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 3,
  },
  korean_zucchini: {
    name: 'korean_zucchini',
    label: '애호박',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 7,
  },
  cabbage: {
    name: 'cabbage',
    label: '양배추',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 14,
  },
  kohlrabi: {
    name: 'kohlrabi',
    label: '콜라비',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 14,
  },
  kabocha: {
    name: 'kabocha',
    label: '단호박',
    category: 'vegetable',
    icon: '',
    defaultStorage: '실온',
    expirationDate: 30,
  },
  garlic_scape: {
    name: 'garlic_scape',
    label: '마늘쫑',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 5,
  },
  lettuce: {
    name: 'lettuce',
    label: '양상추',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 5,
  },
  eolgari: {
    name: 'eolgari',
    label: '얼갈이',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 4,
  },
  red_chard: {
    name: 'red_chard',
    label: '적근대',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 4,
  },
  red_onion: {
    name: 'red_onion',
    label: '적양파',
    category: 'vegetable',
    icon: '',
    defaultStorage: '실온',
    expirationDate: 30,
  },
  chamnamul: {
    name: 'chamnamul',
    label: '참나물',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 3,
  },
  bok_choy: {
    name: 'bok_choy',
    label: '청경채',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 4,
  },
  kongnamul: {
    name: 'kongnamul',
    label: '콩나물',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 3,
  },
  broccoli: {
    name: 'broccoli',
    label: '브로콜리',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 7,
  },
  shiitake: {
    name: 'shiitake',
    label: '표고버섯',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 7,
  },
  wood_ear: {
    name: 'wood_ear',
    label: '목이버섯',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 7,
  },
  sebalnamul: {
    name: 'sebalnamul',
    label: '세발나물',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 3,
  },
  mung_sprout: {
    name: 'mung_sprout',
    label: '숙주나물',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 3,
  },
  red_cabbage: {
    name: 'red_cabbage',
    label: '적양배추',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 14,
  },
  cheongyang_chili: {
    name: 'cheongyang_chili',
    label: '청양고추',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 7,
  },
  enoki: {
    name: 'enoki',
    label: '팽이버섯',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 5,
  },
  oyster_mushroom: {
    name: 'oyster_mushroom',
    label: '느타리버섯',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 5,
  },
  king_oyster: {
    name: 'king_oyster',
    label: '새송이버섯',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 7,
  },
  salad_mix: {
    name: 'salad_mix',
    label: '샐러드믹스',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 3,
  },
  asparagus: {
    name: 'asparagus',
    label: '아스파라거스',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 5,
  },
  yellow_paprika: {
    name: 'yellow_paprika',
    label: '노란파프리카',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 7,
  },
  beech_mushroom: {
    name: 'beech_mushroom',
    label: '만가닥버섯',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 5,
  },
  brussels: {
    name: 'brussels',
    label: '방울양배추',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 7,
  },
  button_mushroom: {
    name: 'button_mushroom',
    label: '양송이버섯',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 5,
  },
  red_pepper: {
    name: 'red_pepper',
    label: '빨간파프리카',
    category: 'vegetable',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 7,
  },
} as const;

const fruitObj = {
  apple_mango: {
    name: 'apple_mango',
    label: '애플망고',
    category: 'fruit',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 5,
  },
  orange: {
    name: 'orange',
    label: '오렌지',
    category: 'fruit',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 14,
  },
  dried_mango: {
    name: 'dried_mango',
    label: '건망고',
    category: 'fruit',
    icon: '',
    defaultStorage: '실온',
    expirationDate: 180,
  },
  kiwi: {
    name: 'kiwi',
    label: '키위',
    category: 'fruit',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 10,
  },
  chamoe: {
    name: 'chamoe',
    label: '참외',
    category: 'fruit',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 7,
  },
  banana: {
    name: 'banana',
    label: '바나나',
    category: 'fruit',
    icon: '',
    defaultStorage: '실온',
    expirationDate: 5,
  },
  tangerine: {
    name: 'tangerine',
    label: '귤',
    category: 'fruit',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 14,
  },
  hallabong: {
    name: 'hallabong',
    label: '한라봉',
    category: 'fruit',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 14,
  },
  watermelon: {
    name: 'watermelon',
    label: '수박',
    category: 'fruit',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 7,
  },
  peach: {
    name: 'peach',
    label: '복숭아',
    category: 'fruit',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 5,
  },
  grape: {
    name: 'grape',
    label: '포도',
    category: 'fruit',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 7,
  },
  ginkgo_nut: {
    name: 'ginkgo_nut',
    label: '은행',
    category: 'fruit',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 7,
  },
  fig: {
    name: 'fig',
    label: '무화과',
    category: 'fruit',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 4,
  },
  plum: {
    name: 'plum',
    label: '자두',
    category: 'fruit',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 5,
  },
  cherry_tomato: {
    name: 'cherry_tomato',
    label: '방울토마토',
    category: 'fruit',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 7,
  },
  cashew: {
    name: 'cashew',
    label: '캐슈넛',
    category: 'fruit',
    icon: '',
    defaultStorage: '실온',
    expirationDate: 120,
  },
  tomato: {
    name: 'tomato',
    label: '토마토',
    category: 'fruit',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 7,
  },
  shine_muscat: {
    name: 'shine_muscat',
    label: '샤인머스캣',
    category: 'fruit',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 10,
  },
  lemon: {
    name: 'lemon',
    label: '레몬',
    category: 'fruit',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 21,
  },
  lime: {
    name: 'lime',
    label: '라임',
    category: 'fruit',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 14,
  },
  avocado: {
    name: 'avocado',
    label: '아보카도',
    category: 'fruit',
    icon: '',
    defaultStorage: '실온',
    expirationDate: 5,
  },
  blueberry: {
    name: 'blueberry',
    label: '블루베리',
    category: 'fruit',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 5,
  },
  pear: {
    name: 'pear',
    label: '배',
    category: 'fruit',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 21,
  },
  almond: {
    name: 'almond',
    label: '아몬드',
    category: 'fruit',
    icon: '',
    defaultStorage: '실온',
    expirationDate: 180,
  },
  raisin: {
    name: 'raisin',
    label: '건포도',
    category: 'fruit',
    icon: '',
    defaultStorage: '실온',
    expirationDate: 365,
  },
  strawberry: {
    name: 'strawberry',
    label: '딸기',
    category: 'fruit',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 3,
  },
  grapefruit: {
    name: 'grapefruit',
    label: '자몽',
    category: 'fruit',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 14,
  },
  sunflower_seed: {
    name: 'sunflower_seed',
    label: '해바라기씨',
    category: 'fruit',
    icon: '',
    defaultStorage: '실온',
    expirationDate: 180,
  },
  pine_nut: {
    name: 'pine_nut',
    label: '잣',
    category: 'fruit',
    icon: '',
    defaultStorage: '실온',
    expirationDate: 90,
  },
  macadamia: {
    name: 'macadamia',
    label: '마카다미아',
    category: 'fruit',
    icon: '',
    defaultStorage: '실온',
    expirationDate: 180,
  },
  pistachio: {
    name: 'pistachio',
    label: '피스타치오',
    category: 'fruit',
    icon: '',
    defaultStorage: '실온',
    expirationDate: 180,
  },
  pineapple: {
    name: 'pineapple',
    label: '파인애플',
    category: 'fruit',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 7,
  },
  cherry: {
    name: 'cherry',
    label: '체리',
    category: 'fruit',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 5,
  },
  persimmon: {
    name: 'persimmon',
    label: '단감',
    category: 'fruit',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 14,
  },
  walnut: {
    name: 'walnut',
    label: '호두',
    category: 'fruit',
    icon: '',
    defaultStorage: '실온',
    expirationDate: 120,
  },
  pomegranate: {
    name: 'pomegranate',
    label: '석류',
    category: 'fruit',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 14,
  },
  melon: {
    name: 'melon',
    label: '멜론',
    category: 'fruit',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 7,
  },
  pumpkin_seed: {
    name: 'pumpkin_seed',
    label: '호박씨',
    category: 'fruit',
    icon: '',
    defaultStorage: '실온',
    expirationDate: 180,
  },
  hazelnut: {
    name: 'hazelnut',
    label: '헤이즐넛',
    category: 'fruit',
    icon: '',
    defaultStorage: '실온',
    expirationDate: 180,
  },
  green_apple: {
    name: 'green_apple',
    label: '초록사과',
    category: 'fruit',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 30,
  },
  peanut: {
    name: 'peanut',
    label: '땅콩',
    category: 'fruit',
    icon: '',
    defaultStorage: '실온',
    expirationDate: 180,
  },
  red_apple: {
    name: 'red_apple',
    label: '빨간사과',
    category: 'fruit',
    icon: '',
    defaultStorage: '냉장',
    expirationDate: 30,
  },
  brazil_nut: {
    name: 'brazil_nut',
    label: '브라질너트',
    category: 'fruit',
    icon: '',
    defaultStorage: '실온',
    expirationDate: 180,
  },
  pecan: {
    name: 'pecan',
    label: '피칸',
    category: 'fruit',
    icon: '',
    defaultStorage: '실온',
    expirationDate: 180,
  },
  chia_seed: {
    name: 'chia_seed',
    label: '치아씨드',
    category: 'fruit',
    icon: '',
    defaultStorage: '실온',
    expirationDate: 365,
  },
} as const;

export const meatObj = {
  skirt_meat: {
    label: '갈매기살',
    name: 'skirt_meat',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['돼지고기'],
    expirationDate: 3,
    synonyms: [],
  },

  egg: {
    label: '계란',
    name: 'egg',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['계란'],
    expirationDate: 21,
    synonyms: [],
  },

  egg_tray: {
    label: '계란판',
    name: 'egg_tray',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['계란'],
    expirationDate: 21,
    synonyms: ['계란'],
  },

  baked_egg: {
    label: '구운계란',
    name: 'baked_egg',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['계란'],
    expirationDate: 7,
    synonyms: [],
  },

  frozen_pork_belly: {
    label: '냉동삼겹살',
    name: 'frozen_pork_belly',
    category: 'meat',
    icon: '',
    defaultStorage: '냉동',
    tags: ['돼지고기'],
    expirationDate: 180,
    synonyms: ['삼겹살'],
  },

  ground_meat: {
    label: '다짐육',
    name: 'ground_meat',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['다진고기'],
    expirationDate: 2,
    synonyms: ['간고기'],
  },

  chicken_breast: {
    label: '닭가슴살',
    name: 'chicken_breast',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['닭고기'],
    expirationDate: 2,
    synonyms: [],
  },

  chicken_wing: {
    label: '닭날개',
    name: 'chicken_wing',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['닭고기'],
    expirationDate: 2,
    synonyms: [],
  },

  chicken_leg: {
    label: '닭다리',
    name: 'chicken_leg',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['닭고기'],
    expirationDate: 2,
    synonyms: [],
  },

  chicken_stew_cut: {
    label: '닭볶음탕용',
    name: 'chicken_stew_cut',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['닭고기'],
    expirationDate: 2,
    synonyms: ['볶음탕용'],
  },

  chicken_tenderloin: {
    label: '닭안심살',
    name: 'chicken_tenderloin',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['닭고기'],
    expirationDate: 2,
    synonyms: [],
  },

  thin_pork_belly: {
    label: '대패삼겹살',
    name: 'thin_pork_belly',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['돼지고기'],
    expirationDate: 3,
    synonyms: [],
  },

  pork_ribs: {
    label: '등갈비',
    name: 'pork_ribs',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['돼지고기'],
    expirationDate: 3,
    synonyms: [],
  },

  pork_loin_slice: {
    label: '등심 잡채용',
    name: 'pork_loin_slice',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['돼지고기'],
    expirationDate: 3,
    synonyms: [],
  },

  pork_loin_cube: {
    label: '등심 카레용',
    name: 'pork_loin_cube',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['돼지고기'],
    expirationDate: 3,
    synonyms: [],
  },

  quail_egg: {
    label: '메추리알',
    name: 'quail_egg',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['계란'],
    expirationDate: 14,
    synonyms: [],
  },

  pork_neck: {
    label: '목살',
    name: 'pork_neck',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['돼지고기'],
    expirationDate: 3,
    synonyms: [],
  },

  soft_boiled_egg: {
    label: '반숙란',
    name: 'soft_boiled_egg',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['계란'],
    expirationDate: 3,
    synonyms: [],
  },

  bacon: {
    label: '베이컨',
    name: 'bacon',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['가공육'],
    expirationDate: 14,
    synonyms: [],
  },

  bulgogi_slice: {
    label: '불고기용',
    name: 'bulgogi_slice',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['소고기'],
    expirationDate: 3,
    synonyms: [],
  },

  vienna_sausage: {
    label: '비엔나소시지',
    name: 'vienna_sausage',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['가공육'],
    expirationDate: 14,
    synonyms: [],
  },

  shank: {
    label: '사태',
    name: 'shank',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['소고기'],
    expirationDate: 3,
    synonyms: [],
  },

  chuck_flap: {
    label: '살치살',
    name: 'chuck_flap',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['소고기'],
    expirationDate: 3,
    synonyms: [],
  },

  pork_belly: {
    label: '삼겹살',
    name: 'pork_belly',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['돼지고기'],
    expirationDate: 3,
    synonyms: [],
  },

  whole_chicken: {
    label: '생닭',
    name: 'whole_chicken',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['닭고기'],
    expirationDate: 2,
    synonyms: [],
  },

  beef_short_rib: {
    label: '소고기 갈비살',
    name: 'beef_short_rib',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['소고기'],
    expirationDate: 3,
    synonyms: [],
  },

  beef_soup_cut: {
    label: '소고기 국거리용',
    name: 'beef_soup_cut',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['소고기'],
    expirationDate: 3,
    synonyms: [],
  },

  beef_shabu_slice: {
    label: '샤브샤브용',
    name: 'beef_shabu_slice',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['소고기'],
    expirationDate: 3,
    synonyms: [],
  },

  beef_short_slice: {
    label: '우삼겹살',
    name: 'beef_short_slice',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['소고기'],
    expirationDate: 3,
    synonyms: [],
  },

  beef_steak: {
    label: '소고기 스테이크',
    name: 'beef_steak',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['소고기'],
    expirationDate: 3,
    synonyms: ['스테이크'],
  },

  beef_tenderloin: {
    label: '소고기 안심',
    name: 'beef_tenderloin',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['소고기'],
    expirationDate: 3,
    synonyms: [],
  },

  beef_brisket: {
    label: '소고기 양지',
    name: 'beef_brisket',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['소고기'],
    expirationDate: 3,
    synonyms: [],
  },

  beef_brisket_slice: {
    label: '소고기 차돌박이',
    name: 'beef_brisket_slice',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['소고기'],
    expirationDate: 3,
    synonyms: [],
  },

  boiled_pork_cut: {
    label: '수육용',
    name: 'boiled_pork_cut',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['돼지고기'],
    expirationDate: 3,
    synonyms: [],
  },

  diet_chicken_breast: {
    label: '식단용 닭가슴살',
    name: 'diet_chicken_breast',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['닭고기'],
    expirationDate: 5,
    synonyms: [],
  },

  beef_shank_special: {
    label: '아롱사태',
    name: 'beef_shank_special',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['소고기'],
    expirationDate: 3,
    synonyms: [],
  },

  outside_skirt: {
    label: '안창살',
    name: 'outside_skirt',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['소고기'],
    expirationDate: 3,
    synonyms: [],
  },

  pork_shoulder_stew: {
    label: '앞다리살 찌개',
    name: 'pork_shoulder_stew',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['돼지고기'],
    expirationDate: 3,
    synonyms: [],
  },

  duck_slice: {
    label: '오리정육슬라이스',
    name: 'duck_slice',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['오리고기'],
    expirationDate: 3,
    synonyms: [],
  },

  smoked_duck_slice: {
    label: '오리훈제슬라이스',
    name: 'smoked_duck_slice',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['오리고기', '훈제'],
    expirationDate: 14,
    synonyms: [],
  },

  round_braise: {
    label: '우둔 장조림용',
    name: 'round_braise',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['소고기'],
    expirationDate: 3,
    synonyms: [],
  },

  braised_short_rib: {
    label: '찜갈비',
    name: 'braised_short_rib',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['소고기'],
    expirationDate: 3,
    synonyms: [],
  },

  sirloin_steak: {
    label: '채끝 스테이크',
    name: 'sirloin_steak',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['소고기'],
    expirationDate: 3,
    synonyms: [],
  },

  jamon: {
    label: '하몽',
    name: 'jamon',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['가공육'],
    expirationDate: 30,
    synonyms: [],
  },

  pork_jowl: {
    label: '항정살',
    name: 'pork_jowl',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['돼지고기'],
    expirationDate: 3,
    synonyms: [],
  },

  tomahawk_steak: {
    label: '토마호크',
    name: 'tomahawk_steak',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['소고기'],
    expirationDate: 3,
    synonyms: [],
  },

  beef_round: {
    label: '홍두깨',
    name: 'beef_round',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['소고기'],
    expirationDate: 3,
    synonyms: [],
  },

  frank_sausage: {
    label: '후랑크소시지',
    name: 'frank_sausage',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['가공육'],
    expirationDate: 14,
    synonyms: [],
  },

  smoked_chicken_breast: {
    label: '훈제닭가슴살',
    name: 'smoked_chicken_breast',
    category: 'meat',
    icon: '',
    defaultStorage: '냉장',
    tags: ['닭고기', '훈제'],
    expirationDate: 14,
    synonyms: [],
  },
} as const;

export const ingredientObj = {
  vegetable: vegetableObj,
  fruit: fruitObj,
  noodle: noodleObj,
  meat: meatObj,
  // seafood: {},
  // grains: {},
  // dairy: {},
  // sidedish: {},
  // conveniencefood: {},
  // seasoning: {},
  // powder: {},
  // desert: {},
  // drink: {},
  // health: {},
  // can: {},
};
