import { StorageItem } from '@/types/storage';
import { Timestamp } from 'firebase/firestore';

export const colorByStorage = {
  blue: {
    bg: 'bg-blue-50',
    pointBg: 'bg-blue-100',
    border: '!border-blue-200',
    text: 'text-blue-700',
  },
  yellow: {
    bg: 'bg-amber-100',
    pointBg: 'bg-amber-200',
    border: '!border-amber-300',
    text: 'text-amber-700',
  },
  green: {
    bg: 'bg-green-100',
    pointBg: 'bg-green-200',
    border: '!border-green-300',
    text: 'text-green-800',
  },
};

export const storageObj = {
  /** 냉동실 */
  freezer: {
    id: 'freezer',
    label: '냉동실',
    side: {
      inner: {
        id: 'inner',
        label: '안쪽',
        sections: [{ id: '1', label: '1번칸' }],
      },
      door: {
        id: 'door',
        label: '문쪽',
        sections: [{ id: '1', label: '1번칸' }],
      },
    },
    order: 1,
    color: 'blue',
  },

  /** 냉장실 */
  fridge: {
    id: 'fridge',
    label: '냉장실',
    side: {
      inner: {
        id: 'inner',
        label: '안쪽',
        sections: [{ id: '1', label: '1번칸' }],
      },
      door: {
        id: 'door',
        label: '문쪽',
        sections: [{ id: '1', label: '1번칸' }],
      },
    },

    order: 2,
    color: 'green',
  },

  /** 실온보관 */
  pantry: {
    id: 'pantry',
    label: '실온보관',
    side: {
      inner: {
        id: 'inner',
        label: '안쪽',
        sections: [{ id: '1', label: '1번칸' }],
      },
      door: {
        id: 'door',
        label: '문쪽',
        sections: [{ id: '1', label: '1번칸' }],
      },
    },
    order: 3,
    color: 'yellow',
  },
} as const;

export const mockStorageItemList: StorageItem[] = [
  {
    id: '1',
    ingredientId: 'egg',
    quantity: 10,
    unitLabel: '개',
    purchasedDate: '2026-03-01',
    expiresAt: '2026-03-21',
    storage: { type: 'fridge', side: 'inner', section: '1' },
    memo: '유정란',
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: '2',
    ingredientId: 'green_onion',
    quantity: 1,
    unitLabel: '단',
    purchasedDate: '2026-03-03',
    storage: { type: 'fridge', side: 'inner', section: '1' },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: '3',
    ingredientId: 'spinach',
    quantity: 1,
    unitLabel: '단',
    purchasedDate: '2026-03-02',
    storage: { type: 'fridge', side: 'inner', section: '1' },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: '4',
    ingredientId: 'broccoli',
    quantity: 1,
    unitLabel: '개',
    purchasedDate: '2026-03-01',
    storage: { type: 'fridge', side: 'inner', section: '1' },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: '5',
    ingredientId: 'korean_zucchini',
    quantity: 2,
    unitLabel: '개',
    purchasedDate: '2026-03-02',
    storage: { type: 'fridge', side: 'inner', section: '1' },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: '6',
    ingredientId: 'shiitake',
    quantity: 1,
    unitLabel: '팩',
    purchasedDate: '2026-03-03',
    storage: { type: 'fridge', side: 'inner', section: '1' },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: '7',
    ingredientId: 'king_oyster',
    quantity: 1,
    unitLabel: '팩',
    purchasedDate: '2026-03-03',
    expiresAt: '2026-03-10',
    storage: { type: 'fridge', side: 'inner', section: '1' },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: '8',
    ingredientId: 'kongnamul',
    quantity: 1,
    unitLabel: '팩',
    purchasedDate: '2026-03-04',
    storage: { type: 'fridge', side: 'inner', section: '1' },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: '9',
    ingredientId: 'mung_sprout',
    quantity: 1,
    unitLabel: '팩',
    purchasedDate: '2026-03-04',
    storage: { type: 'fridge', side: 'inner', section: '1' },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: '10',
    ingredientId: 'cheongyang_chili',
    quantity: 5,
    unitLabel: '개',
    purchasedDate: '2026-03-02',
    storage: { type: 'fridge', side: 'inner', section: '1' },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },

  {
    id: '11',
    ingredientId: 'frozen_pork_belly',
    quantity: 2,
    unitLabel: '팩',
    purchasedDate: '2026-02-10',
    expiresAt: '2026-08-10',
    storage: { type: 'freezer', side: 'inner', section: '1' },
    customLabel: '코스트코 냉동삼겹살',
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: '12',
    ingredientId: 'chicken_breast',
    quantity: 3,
    unitLabel: '팩',
    purchasedDate: '2026-02-25',
    expiresAt: '2026-03-10',
    storage: { type: 'freezer', side: 'inner', section: '1' },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: '13',
    ingredientId: 'duck_slice',
    quantity: 1,
    unitLabel: '팩',
    purchasedDate: '2026-02-28',
    expiresAt: '2026-03-20',
    storage: { type: 'freezer', side: 'inner', section: '1' },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: '14',
    ingredientId: 'smoked_duck_slice',
    quantity: 1,
    unitLabel: '팩',
    purchasedDate: '2026-02-25',
    expiresAt: '2026-04-01',
    storage: { type: 'freezer', side: 'inner', section: '1' },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: '15',
    ingredientId: 'beef_short_rib',
    quantity: 1,
    unitLabel: '팩',
    purchasedDate: '2026-02-20',
    expiresAt: '2026-03-25',
    storage: { type: 'freezer', side: 'inner', section: '1' },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: '16',
    ingredientId: 'bulgogi_slice',
    quantity: 1,
    unitLabel: '팩',
    purchasedDate: '2026-02-18',
    expiresAt: '2026-03-25',
    storage: { type: 'freezer', side: 'inner', section: '1' },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: '17',
    ingredientId: 'pork_neck',
    quantity: 1,
    unitLabel: '팩',
    purchasedDate: '2026-02-27',
    expiresAt: '2026-03-27',
    storage: { type: 'freezer', side: 'inner', section: '1' },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: '18',
    ingredientId: 'beef_shabu_slice',
    quantity: 1,
    unitLabel: '팩',
    purchasedDate: '2026-02-21',
    expiresAt: '2026-03-25',
    storage: { type: 'fridge', side: 'inner', section: '1' },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: '19',
    ingredientId: 'beef_brisket_slice',
    quantity: 1,
    unitLabel: '팩',
    purchasedDate: '2026-02-22',
    expiresAt: '2026-03-25',
    storage: { type: 'freezer', side: 'inner', section: '1' },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: '20',
    ingredientId: 'thin_pork_belly',
    quantity: 2,
    unitLabel: '팩',
    purchasedDate: '2026-02-24',
    expiresAt: '2026-03-28',
    storage: { type: 'freezer', side: 'inner', section: '1' },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },

  {
    id: '21',
    ingredientId: 'spaghetti_noodle',
    quantity: 1,
    unitLabel: '봉',
    purchasedDate: '2026-02-20',
    expiresAt: '2028-02-20',
    storage: { type: 'pantry', side: 'inner', section: '1' },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: '22',
    ingredientId: 'fusilli',
    quantity: 1,
    unitLabel: '봉',
    purchasedDate: '2026-02-15',
    expiresAt: '2028-02-15',
    storage: { type: 'pantry', side: 'inner', section: '1' },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: '23',
    ingredientId: 'buckwheat_noodle',
    quantity: 1,
    unitLabel: '봉',
    purchasedDate: '2026-02-18',
    expiresAt: '2027-02-18',
    storage: { type: 'pantry', side: 'inner', section: '1' },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: '24',
    ingredientId: 'rice_noodle',
    quantity: 1,
    unitLabel: '봉',
    purchasedDate: '2026-02-19',
    expiresAt: '2027-02-19',
    storage: { type: 'pantry', side: 'inner', section: '1' },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: '25',
    ingredientId: 'flat_glass_noodle',
    quantity: 1,
    unitLabel: '봉',
    purchasedDate: '2026-02-15',
    expiresAt: '2028-02-15',
    storage: { type: 'pantry', side: 'inner', section: '1' },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: '26',
    ingredientId: 'rice_paper',
    quantity: 1,
    unitLabel: '팩',
    purchasedDate: '2026-02-10',
    expiresAt: '2027-02-10',
    storage: { type: 'pantry', side: 'inner', section: '1' },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: '27',
    ingredientId: 'tortilla',
    quantity: 1,
    unitLabel: '팩',
    purchasedDate: '2026-03-01',
    expiresAt: '2026-03-31',
    storage: { type: 'fridge', side: 'inner', section: '1' },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: '28',
    ingredientId: 'dumpling_wrapper',
    quantity: 1,
    unitLabel: '팩',
    purchasedDate: '2026-03-02',
    expiresAt: '2026-03-17',
    storage: { type: 'fridge', side: 'inner', section: '1' },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: '29',
    ingredientId: 'tteokbokki_ricecake',
    quantity: 1,
    unitLabel: '봉',
    purchasedDate: '2026-03-03',
    expiresAt: '2026-03-10',
    storage: { type: 'fridge', side: 'inner', section: '1' },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: '30',
    ingredientId: 'kalguksu_noodle',
    quantity: 1,
    unitLabel: '봉',
    purchasedDate: '2026-03-02',
    expiresAt: '2026-04-01',
    storage: { type: 'fridge', side: 'inner', section: '1' },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
];
